INSERT INTO player(rank,name,ovr,pac,sho,pas,dri,def,phy,acceleration,sprint_speed,positioning,finishing,shot_power,long_shots,volleys,penalties,vision,crossing,free_kick_accuracy,short_passing,long_passing,curve,dribbling,agility,balance,reactions,ball_control,composure,interceptions,heading_accuracy,def_awareness,standing_tackle,sliding_tackle,jumping,stamina,strength,aggression,pos,weak_foot,skill_moves,preferred_foot,height,weight,alternative_positions,age,nation,league,team,play_style,url,img,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes) VALUES (17146,'Joy Lysser','53',61,52,48,56,53,58,60,62,55,54,58,48,33,39,50,36,36,57,45,36,54,59,69,52,58,49,50,45,52,58,50,54,60,60,50,'CM',3,2,'Left','170cm / 5''7"','62kg / 137lb',NULL,20,'Switzerland','Schweizer Damen Liga','FC Zürich',NULL,'https://www.ea.com/games/ea-sports-fc/ratings/player-ratings/joy-lysser/276617','https://ratings-images-prod.pulse.ea.com/FC25/full/player-shields/en/276617.png?width=250',NULL,NULL,NULL,NULL,NULL);
INSERT INTO player(rank,name,ovr,pac,sho,pas,dri,def,phy,acceleration,sprint_speed,positioning,finishing,shot_power,long_shots,volleys,penalties,vision,crossing,free_kick_accuracy,short_passing,long_passing,curve,dribbling,agility,balance,reactions,ball_control,composure,interceptions,heading_accuracy,def_awareness,standing_tackle,sliding_tackle,jumping,stamina,strength,aggression,pos,weak_foot,skill_moves,preferred_foot,height,weight,alternative_positions,age,nation,league,team,play_style,url,img,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes) VALUES (17146,'Kateřina Vithová','53',60,49,53,54,27,55,59,60,46,43,58,56,46,54,41,56,57,58,53,55,52,64,65,49,54,40,18,60,23,24,30,66,40,66,42,'LM',3,3,'Left','171cm / 5''7"','64kg / 141lb','LW',18,'Czech Republic','Ceska Liga Žen','Slavia Praha',NULL,'https://www.ea.com/games/ea-sports-fc/ratings/player-ratings/katerina-vithova/275827','https://ratings-images-prod.pulse.ea.com/FC25/full/player-shields/en/275827.png?width=250',NULL,NULL,NULL,NULL,NULL);
-- dummy
INSERT INTO player(rank,name,ovr,pac,sho,pas,dri,def,phy,acceleration,sprint_speed,positioning,finishing,shot_power,long_shots,volleys,penalties,vision,crossing,free_kick_accuracy,short_passing,long_passing,curve,dribbling,agility,balance,reactions,ball_control,composure,interceptions,heading_accuracy,def_awareness,standing_tackle,sliding_tackle,jumping,stamina,strength,aggression,pos,weak_foot,skill_moves,preferred_foot,height,weight,alternative_positions,age,nation,league,team,play_style,url,img,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes) VALUES (99999,'dummy','53',60,49,53,54,27,55,59,60,46,43,58,56,46,54,41,56,57,58,53,55,52,64,65,49,54,40,18,60,23,24,30,66,40,66,42,'LM',3,3,'Left','0','0','LW',18,'','','',NULL,'','',NULL,NULL,NULL,NULL,NULL);
-- team
INSERT INTO team(TEAM,URL) VALUES ('1. FC Köln','https://content.sportslogos.net/logos/132/4075/thumbs/t7j6qkb8hcplgpqskqhhozyee.gif');
INSERT INTO team(TEAM,URL) VALUES ('1. FC Magdeburg','https://content.sportslogos.net/logos/132/5321/thumbs/532151500.gif');
INSERT INTO team(TEAM,URL) VALUES ('1. FC Nürnberg','https://fc25-club-packs.ea.com/uploads/saarbr-cken/emblem/saarbr-cken.png');
INSERT INTO team(TEAM,URL) VALUES ('1. FSV Mainz 05','https://content.sportslogos.net/logos/132/4168/thumbs/2sfzziusrwv73rgqu2dsthtt2.gif');
INSERT INTO team(TEAM,URL) VALUES ('1860 München','https://content.sportslogos.net/logos/129/4892/thumbs/2gg1z5f7wy5eeduf2xpp4wk5m.gif');
INSERT INTO team(TEAM,URL) VALUES ('AC Ajaccio','https://fc25-club-packs.ea.com/uploads/adt/emblem/adt.png');
INSERT INTO team(TEAM,URL) VALUES ('ADT','https://content.sportslogos.net/logos/131/4094/thumbs/ex03n3kj6e5u8f0yhvnh95715.gif');
INSERT INTO team(TEAM,URL) VALUES ('AEK Athens','https://fc25-club-packs.ea.com/uploads/afc-bournemouth/emblem/afc-bournemouth.png');
INSERT INTO team(TEAM,URL) VALUES ('AFC Bournemouth','https://fc25-club-packs.ea.com/uploads/afc-wimbledon/emblem/afc-wimbledon.png');
INSERT INTO team(TEAM,URL) VALUES ('AFC Wimbledon','https://fc25-club-packs.ea.com/uploads/agf/emblem/agf.png');
INSERT INTO team(TEAM,URL) VALUES ('AGF','https://fc25-club-packs.ea.com/uploads/aik/emblem/aik.png');
INSERT INTO team(TEAM,URL) VALUES ('AIK','https://content.sportslogos.net/logos/129/4040/thumbs/jqzdywpqynhmvla3euec5hw0c.gif');
INSERT INTO team(TEAM,URL) VALUES ('AJ Auxerre','https://content.sportslogos.net/logos/131/4097/thumbs/hfkjdeveahia3ymhj7v0o10xc.gif');
INSERT INTO team(TEAM,URL) VALUES ('APOEL FC','https://content.sportslogos.net/logos/129/4041/thumbs/tcet1ae5k3uf8fmwdafgmn8sc.gif');
INSERT INTO team(TEAM,URL) VALUES ('AS Monaco','https://content.sportslogos.net/logos/128/3996/thumbs/eezkjfmm1m7mmg9nm5t0075nh.gif');
INSERT INTO team(TEAM,URL) VALUES ('AS Roma','https://content.sportslogos.net/logos/129/4043/thumbs/a4i8258ae2oh9tza7h38oetju.gif');
INSERT INTO team(TEAM,URL) VALUES ('AS Saint Étienne','https://en.wikipedia.org/wiki/AS_Saint-%C3%89tienne#/media/File:AS_Saint-%C3%89tienne_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('AS Saint-Étienne','https://fc25-club-packs.ea.com/uploads/avs-futebol-sad/emblem/avs-futebol-sad.png');
INSERT INTO team(TEAM,URL) VALUES ('AVS Futebol SAD','https://fc25-club-packs.ea.com/uploads/az/emblem/az.png');
INSERT INTO team(TEAM,URL) VALUES ('AZ','https://fc25-club-packs.ea.com/uploads/aab/emblem/aab.png');
INSERT INTO team(TEAM,URL) VALUES ('AaB','https://content.sportslogos.net/logos/146/4506/thumbs/a2g7begi3igu6727mksnapani.gif');
INSERT INTO team(TEAM,URL) VALUES ('Aberdeen','https://fc25-club-packs.ea.com/uploads/accrington/emblem/accrington.png');
INSERT INTO team(TEAM,URL) VALUES ('Accrington','https://fc25-club-packs.ea.com/uploads/adana-demirspor/emblem/adana-demirspor.png');
INSERT INTO team(TEAM,URL) VALUES ('Adana Demirspor','https://content.sportslogos.net/logos/138/4333/thumbs/b0dzjzc7r6khhjtqgg7g8froe.gif');
INSERT INTO team(TEAM,URL) VALUES ('Adelaide United','https://fc25-club-packs.ea.com/uploads/ajax/emblem/ajax.png');
INSERT INTO team(TEAM,URL) VALUES ('Ajax','https://en.wikipedia.org/wiki/Al-Ahli_Saudi_FC#/media/File:Al_Ahli_Saudi_FC_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('Al Ahli','https://content.sportslogos.net/logos/9/6663/thumbs/666340662021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Al Ain FC','https://content.sportslogos.net/logos/134/4213/thumbs/urerzjaq0gwxy2xwizpfdfw9l.gif');
INSERT INTO team(TEAM,URL) VALUES ('Al Fateh','https://en.wikipedia.org/wiki/Al-Fayha_FC#/media/File:Al-Fayha_FC.svg');
INSERT INTO team(TEAM,URL) VALUES ('Al Fayha','//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Al_Hilal_SFC_Logo.svg/464px-Al_Hilal_SFC_Logo.svg.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Hilal','https://en.wikipedia.org/wiki/Al-Ittihad_Club_(Jeddah)#/media/File:Al-Ittihad_Club_(Jeddah)_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('Al Ittihad','https://fc25-club-packs.ea.com/uploads/al-khaleej/emblem/al-khaleej.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Khaleej','https://fc25-club-packs.ea.com/uploads/al-kholood/emblem/al-kholood.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Kholood','https://content.sportslogos.net/logos/134/4214/thumbs/hptvfbvwnftofy1478tb4a71g.gif');
INSERT INTO team(TEAM,URL) VALUES ('Al Nassr','https://fc25-club-packs.ea.com/uploads/al-okhdood/emblem/al-okhdood.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Okhdood','https://fc25-club-packs.ea.com/uploads/al-orobah/emblem/al-orobah.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Orobah','https://en.wikipedia.org/wiki/Al_Qadsiah_FC#/media/File:Al-Qadsiah_Logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('Al Qadisiyah','https://fc25-club-packs.ea.com/uploads/al-raed/emblem/al-raed.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Raed','https://fc25-club-packs.ea.com/uploads/al-riyadh/emblem/al-riyadh.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Riyadh','https://en.wikipedia.org/wiki/Al_Shabab_FC_(Riyadh)#/media/File:Al_Shabab_FC_(Riyadh).svg');
INSERT INTO team(TEAM,URL) VALUES ('Al Shabab','https://fc25-club-packs.ea.com/uploads/al-taawoun/emblem/al-taawoun.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Taawoun','https://fc25-club-packs.ea.com/uploads/al-wehda/emblem/al-wehda.png');
INSERT INTO team(TEAM,URL) VALUES ('Al Wehda','https://fc25-club-packs.ea.com/uploads/alanyaspor/emblem/alanyaspor.png');
INSERT INTO team(TEAM,URL) VALUES ('Alanyaspor','https://fc25-club-packs.ea.com/uploads/albacete-bp/emblem/albacete-bp.png');
INSERT INTO team(TEAM,URL) VALUES ('Albacete BP','https://fc25-club-packs.ea.com/uploads/aleman-aachen/emblem/aleman-aachen.png');
INSERT INTO team(TEAM,URL) VALUES ('Aleman. Aachen','https://content.sportslogos.net/logos/141/4390/thumbs/9a27rodassfb2hxc024jge7eg.gif');
INSERT INTO team(TEAM,URL) VALUES ('Alianza FC','https://content.sportslogos.net/logos/133/4182/thumbs/o3g079pa4f9brma7jmynhb3mz.gif');
INSERT INTO team(TEAM,URL) VALUES ('Alianza Lima','https://content.sportslogos.net/logos/141/6457/thumbs/645789632017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Almere City FC','https://tmssl.akamaized.net//images/logo/header/b1ap.png?lm=1638148860');
INSERT INTO team(TEAM,URL) VALUES ('Always Ready','https://fc25-club-packs.ea.com/uploads/amiens-sc/emblem/amiens-sc.png');
INSERT INTO team(TEAM,URL) VALUES ('Amiens SC','https://fc25-club-packs.ea.com/uploads/am-rica-de-cali/emblem/am-rica-de-cali.png');
INSERT INTO team(TEAM,URL) VALUES ('América de Cali','https://content.sportslogos.net/logos/141/6457/thumbs/645789632017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Angel City FC','https://content.sportslogos.net/logos/146/4525/thumbs/e4lw4y4mea088ckkbh0bn5bis.gif');
INSERT INTO team(TEAM,URL) VALUES ('Angers SCO','https://content.sportslogos.net/logos/134/4214/thumbs/hptvfbvwnftofy1478tb4a71g.gif');
INSERT INTO team(TEAM,URL) VALUES ('Antalyaspor','https://fc25-club-packs.ea.com/uploads/argentinos-jrs/emblem/argentinos-jrs.png');
INSERT INTO team(TEAM,URL) VALUES ('Argentinos Jrs.','https://fc25-club-packs.ea.com/uploads/arminia-bielefeld/emblem/arminia-bielefeld.png');
INSERT INTO team(TEAM,URL) VALUES ('Arminia Bielefeld','https://content.sportslogos.net/logos/179/5330/thumbs/533037790.gif');
INSERT INTO team(TEAM,URL) VALUES ('Arouca','https://content.sportslogos.net/logos/140/4362/thumbs/g97r5q7mhtcaoitizi3zkyqj7.gif');
INSERT INTO team(TEAM,URL) VALUES ('Arsenal','https://fc25-club-packs.ea.com/uploads/aston-villa/emblem/aston-villa.png');
INSERT INTO team(TEAM,URL) VALUES ('Aston Villa','https://content.sportslogos.net/logos/130/4021/thumbs/6meq6xzglav9fhi4yhfzqxaw4.gif');
INSERT INTO team(TEAM,URL) VALUES ('Athletic Club','https://content.sportslogos.net/logos/133/4202/thumbs/heb32d2tb5drp9pytmt5am6sh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Atl. Nacional','https://content.sportslogos.net/logos/9/5475/thumbs/atlanta_united_fc_logo_primary_2017sportslogosnet3165.gif');
INSERT INTO team(TEAM,URL) VALUES ('Atlanta United','https://content.sportslogos.net/logos/130/4020/thumbs/402014442017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Atlético Tucumán','https://content.sportslogos.net/logos/130/4020/thumbs/402014442017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Atlético de Madrid','https://content.sportslogos.net/logos/142/4433/thumbs/i6uuplo37gxzwz88efgzqzazg.gif');
INSERT INTO team(TEAM,URL) VALUES ('Auckland FC','https://content.sportslogos.net/logos/9/6663/thumbs/666340662021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Austin FC','https://content.sportslogos.net/logos/131/4099/thumbs/e3ahxelpr7efxkmw09h68vgm3.gif');
INSERT INTO team(TEAM,URL) VALUES ('Austria Klagenfurt','https://content.sportslogos.net/logos/132/4072/thumbs/yfkihagcptzem3rhhf4h22343.gif');
INSERT INTO team(TEAM,URL) VALUES ('B. Dortmund II','https://content.sportslogos.net/logos/136/4301/thumbs/430150212012.gif');
INSERT INTO team(TEAM,URL) VALUES ('BK Häcken','https://content.sportslogos.net/logos/131/4155/thumbs/sxfrqpg9enyf37ueggbn0eygf.gif');
INSERT INTO team(TEAM,URL) VALUES ('BSC Young Boys','https://content.sportslogos.net/logos/179/5341/thumbs/534136560.gif');
INSERT INTO team(TEAM,URL) VALUES ('Banfield','https://content.sportslogos.net/logos/130/4016/thumbs/hy5fvvdkee83gg3r5ym22zr5o.gif');
INSERT INTO team(TEAM,URL) VALUES ('Barcelona SC','https://content.sportslogos.net/logos/128/4015/thumbs/7kqyvqv5bzbg0jfr5kjceg4pb.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bari','https://fc25-club-packs.ea.com/uploads/barnsley/emblem/barnsley.png');
INSERT INTO team(TEAM,URL) VALUES ('Barnsley','https://fc25-club-packs.ea.com/uploads/barracas-central/emblem/barracas-central.png');
INSERT INTO team(TEAM,URL) VALUES ('Barracas Central','https://fc25-club-packs.ea.com/uploads/barrow/emblem/barrow.png');
INSERT INTO team(TEAM,URL) VALUES ('Barrow','https://en.wikipedia.org/wiki/%C4%B0stanbul_Ba%C5%9Fak%C5%9Fehir_F.K.#/media/File:%C4%B0stanbul_Ba%C5%9Fak%C5%9Fehir_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('Bay FC','https://content.sportslogos.net/logos/231/6716/thumbs/671697262019.gif');
INSERT INTO team(TEAM,URL) VALUES ('Başakşehir','https://content.sportslogos.net/logos/152/4631/thumbs/d8lqtv8wzwjaotyrmpn7py5qp.gif');
INSERT INTO team(TEAM,URL) VALUES ('Beijing FC','https://fc25-club-packs.ea.com/uploads/belgrano/emblem/belgrano.png');
INSERT INTO team(TEAM,URL) VALUES ('Belgrano','https://content.sportslogos.net/logos/231/6721/thumbs/672122292019.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bengaluru FC','https://en.wikipedia.org/wiki/Atalanta_BC#/media/File:AtalantaBC.svg');
INSERT INTO team(TEAM,URL) VALUES ('Bergamo Calcio','https://content.sportslogos.net/logos/131/4102/thumbs/nhp900z8u2afqten07erwfetv.gif');
INSERT INTO team(TEAM,URL) VALUES ('Beşiktaş','https://content.sportslogos.net/logos/141/5957/thumbs/595772802016.gif');
INSERT INTO team(TEAM,URL) VALUES ('Birmingham City','https://content.sportslogos.net/logos/52/1358/thumbs/6058.gif');
INSERT INTO team(TEAM,URL) VALUES ('Blackburn Rovers','https://fc25-club-packs.ea.com/uploads/blackpool/emblem/blackpool.png');
INSERT INTO team(TEAM,URL) VALUES ('Blackpool','https://fc25-club-packs.ea.com/uploads/blau-weiss-linz/emblem/blau-weiss-linz.png');
INSERT INTO team(TEAM,URL) VALUES ('Blau-Weiss Linz','https://content.sportslogos.net/logos/132/4072/thumbs/yfkihagcptzem3rhhf4h22343.gif');
INSERT INTO team(TEAM,URL) VALUES ('BoRussian Federation Dortmund','https://content.sportslogos.net/logos/179/5333/thumbs/533349180.gif');
INSERT INTO team(TEAM,URL) VALUES ('Boavista FC','https://content.sportslogos.net/logos/133/4188/thumbs/teg1hporjgd5qp70eaz16p5n7.gif');
INSERT INTO team(TEAM,URL) VALUES ('Boca Juniors','https://fc25-club-packs.ea.com/uploads/bodrum-fk/emblem/bodrum-fk.png');
INSERT INTO team(TEAM,URL) VALUES ('Bodrum FK','https://content.sportslogos.net/logos/125/3830/thumbs/3zj70406y3ar3rc8nuodkw5uz.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bohemians','https://content.sportslogos.net/logos/133/4192/thumbs/i7ukyyaeug4rilm19cebwpxax.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bologna','https://content.sportslogos.net/logos/128/3995/thumbs/nog8pjquy63c99jc4h79h8fpe.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bolton','https://content.sportslogos.net/logos/128/3995/thumbs/nog8pjquy63c99jc4h79h8fpe.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bolívar','https://content.sportslogos.net/logos/124/5938/thumbs/593832902016.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bradford City','https://fc25-club-packs.ea.com/uploads/braunschweig/emblem/braunschweig.png');
INSERT INTO team(TEAM,URL) VALUES ('Braunschweig','https://fc25-club-packs.ea.com/uploads/brentford/emblem/brentford.png');
INSERT INTO team(TEAM,URL) VALUES ('Brentford','https://content.sportslogos.net/logos/131/4102/thumbs/nhp900z8u2afqten07erwfetv.gif');
INSERT INTO team(TEAM,URL) VALUES ('Brescia','https://fc25-club-packs.ea.com/uploads/brighton/emblem/brighton.png');
INSERT INTO team(TEAM,URL) VALUES ('Brighton','https://content.sportslogos.net/logos/138/4334/thumbs/433485462015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Brisbane Roar','https://content.sportslogos.net/logos/141/5949/thumbs/594960432016.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bristol City','https://content.sportslogos.net/logos/52/1358/thumbs/6058.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bristol Rovers','https://content.sportslogos.net/logos/160/4905/thumbs/490526890.gif');
INSERT INTO team(TEAM,URL) VALUES ('Bromley FC','https://fc25-club-packs.ea.com/uploads/brommapojkarna/emblem/brommapojkarna.png');
INSERT INTO team(TEAM,URL) VALUES ('Brommapojkarna','https://content.sportslogos.net/logos/160/4905/thumbs/490526890.gif');
INSERT INTO team(TEAM,URL) VALUES ('Brøndby IF','https://fc25-club-packs.ea.com/uploads/burgos-cf/emblem/burgos-cf.png');
INSERT INTO team(TEAM,URL) VALUES ('Burgos CF','https://fc25-club-packs.ea.com/uploads/burnley/emblem/burnley.png');
INSERT INTO team(TEAM,URL) VALUES ('Burnley','https://content.sportslogos.net/logos/127/3926/thumbs/ydeool7qiiaf59ytbnfkm38e5.gif');
INSERT INTO team(TEAM,URL) VALUES ('Burton Albion','https://content.sportslogos.net/logos/129/4058/thumbs/e547f0ce55e7zgfjiev75c56f.gif');
INSERT INTO team(TEAM,URL) VALUES ('CA Osasuna','https://content.sportslogos.net/logos/130/4027/thumbs/zj7eqoh45gw4ula6qghqfqy4g.gif');
INSERT INTO team(TEAM,URL) VALUES ('CD Castellón','https://content.sportslogos.net/logos/131/4116/thumbs/v9zc7h8cx86h0gi5g1nzmbbge.gif');
INSERT INTO team(TEAM,URL) VALUES ('CD Eldense','https://fc25-club-packs.ea.com/uploads/cd-eldense/emblem/cd-eldense.png');
INSERT INTO team(TEAM,URL) VALUES ('CD Leganés','https://content.sportslogos.net/logos/128/3992/thumbs/nwfgf6g3d2ut2c2q2sopm6sje.gif');
INSERT INTO team(TEAM,URL) VALUES ('CD MIran, Islamic Republic ofdés','https://content.sportslogos.net/logos/180/5354/thumbs/535467030.gif');
INSERT INTO team(TEAM,URL) VALUES ('CD Tenerife','https://content.sportslogos.net/logos/9/6754/thumbs/675474412023.gif');
INSERT INTO team(TEAM,URL) VALUES ('CF Montréal','https://content.sportslogos.net/logos/131/4106/thumbs/8k2zclwn3yqcfde0boo4e6qrf.gif');
INSERT INTO team(TEAM,URL) VALUES ('CFR 1907 Cluj','https://en.wikipedia.org/wiki/C%C3%A1diz_CF#/media/File:C%C3%A1diz_CF_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('Cagliari','https://content.sportslogos.net/logos/128/4007/thumbs/1ianseq4hpm669hg449dg5ahb.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cambridge Utd','https://fc25-club-packs.ea.com/uploads/cambridge-utd/emblem/cambridge-utd.png');
INSERT INTO team(TEAM,URL) VALUES ('Cangzhou FC','https://content.sportslogos.net/logos/152/4636/thumbs/i88b0zvg2je1ut772iy8eryha.gif');
INSERT INTO team(TEAM,URL) VALUES ('Carabobo FC','https://content.sportslogos.net/logos/141/4394/thumbs/w4lbdm03d8y5oxkgf4hahkt96.gif');
INSERT INTO team(TEAM,URL) VALUES ('Caracas FC','https://content.sportslogos.net/logos/204/5927/thumbs/592796052016.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cardiff City','https://content.sportslogos.net/logos/141/4422/thumbs/1vfhy7x2g1c739tambyfupjb7.gif');
INSERT INTO team(TEAM,URL) VALUES ('Carl Zeiss Jena','https://fc25-club-packs.ea.com/uploads/carl-zeiss-jena/emblem/carl-zeiss-jena.png');
INSERT INTO team(TEAM,URL) VALUES ('Carlisle United','https://content.sportslogos.net/logos/141/5882/thumbs/588261822015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Carrarese Calcio','https://fc25-club-packs.ea.com/uploads/carrarese-calcio/emblem/carrarese-calcio.png');
INSERT INTO team(TEAM,URL) VALUES ('Casa Pia AC','https://content.sportslogos.net/logos/204/5927/thumbs/592796052016.gif');
INSERT INTO team(TEAM,URL) VALUES ('Catanzaro','https://content.sportslogos.net/logos/128/4006/thumbs/o4i4gh0r9f4zucr8jmebn0eez.gif');
INSERT INTO team(TEAM,URL) VALUES ('Celtic','https://fc25-club-packs.ea.com/uploads/aykur-rizespor/emblem/aykur-rizespor.png');
INSERT INTO team(TEAM,URL) VALUES ('Central Coast','https://content.sportslogos.net/logos/146/4507/thumbs/0bth7jqxzj5n71rhomfn7rg8f.gif');
INSERT INTO team(TEAM,URL) VALUES ('Central Córdoba','https://content.sportslogos.net/logos/138/4335/thumbs/68l6fg7xezo04fsq6ufzfieeo.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cercle Brugge','https://content.sportslogos.net/logos/125/3878/thumbs/8r4oa0klqae7tbfui28rczn08.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cerro Largo','https://content.sportslogos.net/logos/131/4107/thumbs/5q52z5mgylcyb3yf3p5fg24f4.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cerro Porteño','https://fc25-club-packs.ea.com/uploads/cerro-largo/emblem/cerro-largo.png');
INSERT INTO team(TEAM,URL) VALUES ('Cesena','https://content.sportslogos.net/logos/179/5342/thumbs/534228680.gif');
INSERT INTO team(TEAM,URL) VALUES ('Changchun Yatai','https://content.sportslogos.net/logos/128/4012/thumbs/8eq92si2dwkbes6te9ff91fhi.gif');
INSERT INTO team(TEAM,URL) VALUES ('Charlotte FC','https://content.sportslogos.net/logos/152/4632/thumbs/mp5oggfj8tbyg98giqo98b8h9.gif');
INSERT INTO team(TEAM,URL) VALUES ('Charlton Ath','https://content.sportslogos.net/logos/9/6739/thumbs/673957692022.gif');
INSERT INTO team(TEAM,URL) VALUES ('Chelsea','https://content.sportslogos.net/logos/135/4241/thumbs/9fkfp5gcfh5xzxzshg4geu6v1.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cheltenham Town','https://content.sportslogos.net/logos/128/4012/thumbs/8eq92si2dwkbes6te9ff91fhi.gif');
INSERT INTO team(TEAM,URL) VALUES ('Chennaiyin FC','https://fc25-club-packs.ea.com/uploads/cheltenham-town/emblem/cheltenham-town.png');
INSERT INTO team(TEAM,URL) VALUES ('Chesterfield','https://content.sportslogos.net/logos/141/4422/thumbs/1vfhy7x2g1c739tambyfupjb7.gif');
INSERT INTO team(TEAM,URL) VALUES ('Chicago Fire FC','https://content.sportslogos.net/logos/141/5905/thumbs/590513682014.gif');
INSERT INTO team(TEAM,URL) VALUES ('Chicago Red Stars','https://content.sportslogos.net/logos/9/323/thumbs/32390352022.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cittadella','https://content.sportslogos.net/logos/202/5865/thumbs/586516512017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Clermont Foot 63','https://fc25-club-packs.ea.com/uploads/cittadella/emblem/cittadella.png');
INSERT INTO team(TEAM,URL) VALUES ('Club Brugge','https://fc25-club-packs.ea.com/uploads/clermont-foot-63/emblem/clermont-foot-63.png');
INSERT INTO team(TEAM,URL) VALUES ('Club Nacional','https://content.sportslogos.net/logos/131/4107/thumbs/5q52z5mgylcyb3yf3p5fg24f4.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cobresal','https://content.sportslogos.net/logos/133/4202/thumbs/heb32d2tb5drp9pytmt5am6sh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Colchester','https://content.sportslogos.net/logos/124/5486/thumbs/548678982015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Colo-Colo','https://content.sportslogos.net/logos/126/3915/thumbs/m8vh8epwj3lsjrmg0nfh4wdbw.gif');
INSERT INTO team(TEAM,URL) VALUES ('Colorado Rapids','https://content.sportslogos.net/logos/133/4195/thumbs/kck5p1hb7zhbsta10yf3byo82.gif');
INSERT INTO team(TEAM,URL) VALUES ('Columbus Crew','https://content.sportslogos.net/logos/9/328/thumbs/colorado_rapids_logo_primary_2007sportslogosnet6380.gif');
INSERT INTO team(TEAM,URL) VALUES ('Como','https://content.sportslogos.net/logos/9/324/thumbs/32439272021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Coquimbo Unido','https://fc25-club-packs.ea.com/uploads/como/emblem/como.png');
INSERT INTO team(TEAM,URL) VALUES ('Cosenza','https://fc25-club-packs.ea.com/uploads/coquimbo-unido/emblem/coquimbo-unido.png');
INSERT INTO team(TEAM,URL) VALUES ('Coventry City','https://fc25-club-packs.ea.com/uploads/c-rdoba-cf/emblem/c-rdoba-cf.png');
INSERT INTO team(TEAM,URL) VALUES ('Cracovia','https://content.sportslogos.net/logos/128/4012/thumbs/8eq92si2dwkbes6te9ff91fhi.gif');
INSERT INTO team(TEAM,URL) VALUES ('Crawley Town','https://content.sportslogos.net/logos/52/1377/thumbs/hdd4efpf78qg631npfyr6ecnk.gif');
INSERT INTO team(TEAM,URL) VALUES ('Cremonese','https://fc25-club-packs.ea.com/uploads/cracovia/emblem/cracovia.png');
INSERT INTO team(TEAM,URL) VALUES ('Crewe Alexandra','https://fc25-club-packs.ea.com/uploads/crawley-town/emblem/crawley-town.png');
INSERT INTO team(TEAM,URL) VALUES ('Crystal Palace','https://fc25-club-packs.ea.com/uploads/cremonese/emblem/cremonese.png');
INSERT INTO team(TEAM,URL) VALUES ('Cádiz CF','https://fc25-club-packs.ea.com/uploads/crewe-alexandra/emblem/crewe-alexandra.png');
INSERT INTO team(TEAM,URL) VALUES ('Córdoba CF','https://content.sportslogos.net/logos/126/3920/thumbs/omsciu62ssle3n62hedxwtmnx.gif');
INSERT INTO team(TEAM,URL) VALUES ('D. Alavés','https://fc25-club-packs.ea.com/uploads/d-alav-s/emblem/d-alav-s.png');
INSERT INTO team(TEAM,URL) VALUES ('D.C. United','https://content.sportslogos.net/logos/9/325/thumbs/32590012016.gif');
INSERT INTO team(TEAM,URL) VALUES ('Daegu FC','https://content.sportslogos.net/logos/151/4611/thumbs/fgz9pnoyyoh18awmhowy5ngt3.gif');
INSERT INTO team(TEAM,URL) VALUES ('Daejeon','https://fc25-club-packs.ea.com/uploads/daejeon/emblem/daejeon.png');
INSERT INTO team(TEAM,URL) VALUES ('Damac FC','https://content.sportslogos.net/logos/126/3919/thumbs/70khrkvz0h9ql032sggfaekg7.gif');
INSERT INTO team(TEAM,URL) VALUES ('Danubio','https://fc25-club-packs.ea.com/uploads/danubio/emblem/danubio.png');
INSERT INTO team(TEAM,URL) VALUES ('Defensa','https://content.sportslogos.net/logos/128/4012/thumbs/8eq92si2dwkbes6te9ff91fhi.gif');
INSERT INTO team(TEAM,URL) VALUES ('Delfín SC','https://fc25-club-packs.ea.com/uploads/delf-n-sc/emblem/delf-n-sc.png');
INSERT INTO team(TEAM,URL) VALUES ('Dep. Cuenca','https://fc25-club-packs.ea.com/uploads/dep-cuenca/emblem/dep-cuenca.png');
INSERT INTO team(TEAM,URL) VALUES ('Dep. Garcilaso','https://fc25-club-packs.ea.com/uploads/dep-garcilaso/emblem/dep-garcilaso.png');
INSERT INTO team(TEAM,URL) VALUES ('Dep. La Guaira','https://fc25-club-packs.ea.com/uploads/dep-la-guaira/emblem/dep-la-guaira.png');
INSERT INTO team(TEAM,URL) VALUES ('Dep. Riestra','https://fc25-club-packs.ea.com/uploads/dep-riestra/emblem/dep-riestra.png');
INSERT INTO team(TEAM,URL) VALUES ('Dep. Táchira','https://fc25-club-packs.ea.com/uploads/deportes-tolima/emblem/deportes-tolima.png');
INSERT INTO team(TEAM,URL) VALUES ('Deportes Tolima','https://content.sportslogos.net/logos/130/4023/thumbs/lspwi1bjub5ttlt6dq60lrlso.gif');
INSERT INTO team(TEAM,URL) VALUES ('Derby County','https://fc25-club-packs.ea.com/uploads/derby-county/emblem/derby-county.png');
INSERT INTO team(TEAM,URL) VALUES ('Derry City','https://content.sportslogos.net/logos/141/4404/thumbs/7mh138f6ptwrdyaaplhpd8c4m.gif');
INSERT INTO team(TEAM,URL) VALUES ('Dijon FCO','https://content.sportslogos.net/logos/129/4044/thumbs/i14qf7zjomo5gq4a4fw2h0jpr.gif');
INSERT INTO team(TEAM,URL) VALUES ('Dinamo Zagreb','https://content.sportslogos.net/logos/144/4469/thumbs/ovpzjza4ebuo9hafjytgejypf.gif');
INSERT INTO team(TEAM,URL) VALUES ('Djurgårdens IF','https://content.sportslogos.net/logos/136/4297/thumbs/r0u6hfsm53k1gif4lgnfkfaz1.gif');
INSERT INTO team(TEAM,URL) VALUES ('Doncaster','https://fc25-club-packs.ea.com/uploads/doncaster/emblem/doncaster.png');
INSERT INTO team(TEAM,URL) VALUES ('Drogheda United','https://content.sportslogos.net/logos/125/6483/thumbs/648362882017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Dundalk','https://fc25-club-packs.ea.com/uploads/dundalk/emblem/dundalk.png');
INSERT INTO team(TEAM,URL) VALUES ('Dundee FC','https://content.sportslogos.net/logos/146/4508/thumbs/uga1v2nygffrk08ftrgkjlfpk.gif');
INSERT INTO team(TEAM,URL) VALUES ('Dundee United','https://content.sportslogos.net/logos/146/4508/thumbs/uga1v2nygffrk08ftrgkjlfpk.gif');
INSERT INTO team(TEAM,URL) VALUES ('Dynamo Dresden','https://content.sportslogos.net/logos/132/4165/thumbs/d4pp7q9gli5gxg2ieqdszcoh8.gif');
INSERT INTO team(TEAM,URL) VALUES ('Dynamo Kyiv','https://content.sportslogos.net/logos/131/4111/thumbs/eb21umca58br687loy1oecegl.gif');
INSERT INTO team(TEAM,URL) VALUES ('Düsseldorf','https://content.sportslogos.net/logos/140/4365/thumbs/y0hez3uqnewu1n5gq6u6vqrf2.gif');
INSERT INTO team(TEAM,URL) VALUES ('ESTAC Troyes','https://content.sportslogos.net/logos/129/4065/thumbs/i3cgioegeb8hdcm5p966z8p6u.gif');
INSERT INTO team(TEAM,URL) VALUES ('East Bengal','https://fc25-club-packs.ea.com/uploads/east-bengal/emblem/east-bengal.png');
INSERT INTO team(TEAM,URL) VALUES ('Elche CF','https://fc25-club-packs.ea.com/uploads/elche-cf/emblem/elche-cf.png');
INSERT INTO team(TEAM,URL) VALUES ('Empoli','https://content.sportslogos.net/logos/128/3999/thumbs/ig0qxnu0hsyvb5eugex7k50uh.gif');
INSERT INTO team(TEAM,URL) VALUES ('En Avant Guingamp','https://content.sportslogos.net/logos/129/4049/thumbs/ntzfhqq4bo4jtheyww8gd3hco.gif');
INSERT INTO team(TEAM,URL) VALUES ('Energie Cottbus','https://fc25-club-packs.ea.com/uploads/energie-cottbus/emblem/energie-cottbus.png');
INSERT INTO team(TEAM,URL) VALUES ('Estoril Praia','https://content.sportslogos.net/logos/179/5335/thumbs/533592890.gif');
INSERT INTO team(TEAM,URL) VALUES ('Estrela Amadora','https://fc25-club-packs.ea.com/uploads/estrela-amadora/emblem/estrela-amadora.png');
INSERT INTO team(TEAM,URL) VALUES ('Estudiantes','https://fc25-club-packs.ea.com/uploads/estudiantes/emblem/estudiantes.png');
INSERT INTO team(TEAM,URL) VALUES ('Ettifaq FC','https://fc25-club-packs.ea.com/uploads/ettifaq-fc/emblem/ettifaq-fc.png');
INSERT INTO team(TEAM,URL) VALUES ('Everton','https://fc25-club-packs.ea.com/uploads/everton/emblem/everton.png');
INSERT INTO team(TEAM,URL) VALUES ('Exeter City','https://content.sportslogos.net/logos/141/5607/thumbs/560774602013.gif');
INSERT INTO team(TEAM,URL) VALUES ('Eyüpspor','https://fc25-club-packs.ea.com/uploads/ey-pspor/emblem/ey-pspor.png');
INSERT INTO team(TEAM,URL) VALUES ('F.C. København','https://content.sportslogos.net/logos/160/4912/thumbs/491223001992.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Annecy','https://content.sportslogos.net/logos/127/3942/thumbs/yj2kdg9ggzrajfycartkg3i3m.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Augsburg','https://content.sportslogos.net/logos/132/4082/thumbs/408243350.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Barcelona','https://content.sportslogos.net/logos/130/4016/thumbs/hy5fvvdkee83gg3r5ym22zr5o.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Basel 1893','https://content.sportslogos.net/logos/131/4116/thumbs/v9zc7h8cx86h0gi5g1nzmbbge.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Bayern München','https://content.sportslogos.net/logos/132/4069/thumbs/rr72mhpas38h85jdw85neas5f.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Boto?ani','https://content.sportslogos.net/logos/125/6469/thumbs/646926722015.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Cartagena','https://content.sportslogos.net/logos/130/4016/thumbs/hy5fvvdkee83gg3r5ym22zr5o.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Cincinnati','https://content.sportslogos.net/logos/124/5871/thumbs/587146062016.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Dallas','https://content.sportslogos.net/logos/9/329/thumbs/97yz6vcggd25lhyswy2fgvhfz.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Dinamo 1948','https://fc25-club-packs.ea.com/uploads/fc-dinamo-1948/emblem/fc-dinamo-1948.png');
INSERT INTO team(TEAM,URL) VALUES ('FC Erzgebirge Aue','https://fc25-club-packs.ea.com/uploads/fc-erzgebirge-aue/emblem/fc-erzgebirge-aue.png');
INSERT INTO team(TEAM,URL) VALUES ('FC Famalicão','https://en.wikipedia.org/wiki/F.C._Famalic%C3%A3o#/media/File:F.C._Famalic%C3%A3o_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('FC Fleury 91','https://content.sportslogos.net/logos/125/6501/thumbs/650160802017.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Gloria Buzău','https://fc25-club-packs.ea.com/uploads/fc-gloria-buz-u/emblem/fc-gloria-buz-u.png');
INSERT INTO team(TEAM,URL) VALUES ('FC Goa','https://content.sportslogos.net/logos/132/4075/thumbs/t7j6qkb8hcplgpqskqhhozyee.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Groningen','https://content.sportslogos.net/logos/180/5353/thumbs/535335730.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Hansa Rostock','https://content.sportslogos.net/logos/202/5866/thumbs/586611942013.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Hermannstadt','https://content.sportslogos.net/logos/141/4408/thumbs/tmgrmgj8hfcuyb4lm7b4p7bdn.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Ingolstadt 04','https://fc25-club-packs.ea.com/uploads/fc-ingolstadt-04/emblem/fc-ingolstadt-04.png');
INSERT INTO team(TEAM,URL) VALUES ('FC Lorient','https://content.sportslogos.net/logos/179/5342/thumbs/534228680.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Lugano','https://content.sportslogos.net/logos/141/4406/thumbs/bs9qe9wnspfnovfx91pfgtpxg.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Luzern','https://content.sportslogos.net/logos/129/4058/thumbs/e547f0ce55e7zgfjiev75c56f.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Martigues','https://content.sportslogos.net/logos/132/4082/thumbs/408243350.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Metz','https://content.sportslogos.net/logos/129/4160/thumbs/7z6fu6gjk6exjf70iuwu6z0ne.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Midtjylland','https://content.sportslogos.net/logos/129/4048/thumbs/ah3p1ojexa59o4qpttvi3h6md.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Nantes','https://content.sportslogos.net/logos/160/4907/thumbs/490779211999.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Nordsjælland','https://content.sportslogos.net/logos/129/4160/thumbs/7z6fu6gjk6exjf70iuwu6z0ne.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Petrolul','https://content.sportslogos.net/logos/160/4913/thumbs/491359122003.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Porto','https://content.sportslogos.net/logos/151/4599/thumbs/eh0y6mke9rgjv3xmgml3dtn68.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Rapid 1923','https://content.sportslogos.net/logos/179/5342/thumbs/534228680.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Rosengård','https://fc25-club-packs.ea.com/uploads/fc-rapid-1923/emblem/fc-rapid-1923.png');
INSERT INTO team(TEAM,URL) VALUES ('FC Schalke 04','https://content.sportslogos.net/logos/141/4408/thumbs/tmgrmgj8hfcuyb4lm7b4p7bdn.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Seoul','https://content.sportslogos.net/logos/132/4081/thumbs/13p1uwdmg16hnw8cq4cut4u9z.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Sion','https://content.sportslogos.net/logos/151/4599/thumbs/eh0y6mke9rgjv3xmgml3dtn68.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC St. Gallen','https://content.sportslogos.net/logos/132/4075/thumbs/t7j6qkb8hcplgpqskqhhozyee.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC St. Pauli','https://fc25-club-packs.ea.com/uploads/fc-st-gallen/emblem/fc-st-gallen.png');
INSERT INTO team(TEAM,URL) VALUES ('FC Twente','https://content.sportslogos.net/logos/126/3923/thumbs/da899ciaaecygrqz7t9fy4g4e.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Univ. Cluj','https://content.sportslogos.net/logos/180/5354/thumbs/535467030.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Utrecht','https://fc25-club-packs.ea.com/uploads/fc-univ-cluj/emblem/fc-univ-cluj.png');
INSERT INTO team(TEAM,URL) VALUES ('FC Winterthur','https://content.sportslogos.net/logos/180/5355/thumbs/535535540.gif');
INSERT INTO team(TEAM,URL) VALUES ('FC Zürich','https://content.sportslogos.net/logos/161/4924/thumbs/492483191990.gif');
INSERT INTO team(TEAM,URL) VALUES ('FCSB','https://content.sportslogos.net/logos/131/4119/thumbs/pu04qj24ghioh0xh42j6ane8l.gif');
INSERT INTO team(TEAM,URL) VALUES ('FCV Dender EH','https://fc25-club-packs.ea.com/uploads/fcsb/emblem/fcsb.png');
INSERT INTO team(TEAM,URL) VALUES ('FK Austria Wien','https://fc25-club-packs.ea.com/uploads/fcv-dender-eh/emblem/fcv-dender-eh.png');
INSERT INTO team(TEAM,URL) VALUES ('FK Bodø/Glimt','https://content.sportslogos.net/logos/131/4099/thumbs/e3ahxelpr7efxkmw09h68vgm3.gif');
INSERT INTO team(TEAM,URL) VALUES ('FK Haugesund','https://fc25-club-packs.ea.com/uploads/fk-bod-glimt/emblem/fk-bod-glimt.png');
INSERT INTO team(TEAM,URL) VALUES ('Farense','https://fc25-club-packs.ea.com/uploads/fk-haugesund/emblem/fk-haugesund.png');
INSERT INTO team(TEAM,URL) VALUES ('Farul Constan?a','https://content.sportslogos.net/logos/132/4079/thumbs/ulym34kee4tbfgo4j1pb8ol2f.gif');
INSERT INTO team(TEAM,URL) VALUES ('Fenerbahçe','https://content.sportslogos.net/logos/179/5347/thumbs/534787530.gif');
INSERT INTO team(TEAM,URL) VALUES ('Ferencvárosi TC','https://fc25-club-packs.ea.com/uploads/farul-constan-a/emblem/farul-constan-a.png');
INSERT INTO team(TEAM,URL) VALUES ('Feyenoord','https://content.sportslogos.net/logos/131/4170/thumbs/w1tfsygyong1nc5yfgen9ckie.gif');
INSERT INTO team(TEAM,URL) VALUES ('Fiorentina','https://en.wikipedia.org/wiki/Ferencv%C3%A1rosi_TC#/media/File:Ferencvarosi_TC.svg');
INSERT INTO team(TEAM,URL) VALUES ('Fleetwood Town','https://content.sportslogos.net/logos/180/5358/thumbs/535852370.gif');
INSERT INTO team(TEAM,URL) VALUES ('Fortuna Sittard','https://content.sportslogos.net/logos/128/4011/thumbs/dzte7053fk19cxjbc7sfmgt6h.gif');
INSERT INTO team(TEAM,URL) VALUES ('Frankfurt','https://fc25-club-packs.ea.com/uploads/fleetwood-town/emblem/fleetwood-town.png');
INSERT INTO team(TEAM,URL) VALUES ('Fredrikstad FK','https://fc25-club-packs.ea.com/uploads/fortuna-sittard/emblem/fortuna-sittard.png');
INSERT INTO team(TEAM,URL) VALUES ('Frosinone','https://content.sportslogos.net/logos/132/4077/thumbs/u8wdhb5sjmg0ntnahm5aefzhl.gif');
INSERT INTO team(TEAM,URL) VALUES ('Fulham','https://content.sportslogos.net/logos/141/5881/thumbs/588195672015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Fürth','https://fc25-club-packs.ea.com/uploads/frosinone/emblem/frosinone.png');
INSERT INTO team(TEAM,URL) VALUES ('GAIS','https://fc25-club-packs.ea.com/uploads/fulham/emblem/fulham.png');
INSERT INTO team(TEAM,URL) VALUES ('GC Zürich','https://fc25-club-packs.ea.com/uploads/f-rth/emblem/f-rth.png');
INSERT INTO team(TEAM,URL) VALUES ('GKS Katowice','https://fc25-club-packs.ea.com/uploads/gais/emblem/gais.png');
INSERT INTO team(TEAM,URL) VALUES ('Galatasaray','https://content.sportslogos.net/logos/131/4119/thumbs/pu04qj24ghioh0xh42j6ane8l.gif');
INSERT INTO team(TEAM,URL) VALUES ('Galway United','https://fc25-club-packs.ea.com/uploads/gks-katowice/emblem/gks-katowice.png');
INSERT INTO team(TEAM,URL) VALUES ('Gangwon FC','https://content.sportslogos.net/logos/131/4124/thumbs/0xbvffz8pbhxcf60i2f2tuq0u.gif');
INSERT INTO team(TEAM,URL) VALUES ('Gaziantep','https://content.sportslogos.net/logos/204/5974/thumbs/597411922015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Genoa','https://content.sportslogos.net/logos/151/4622/thumbs/4mkqyy815k6e262yupdwklhie.gif');
INSERT INTO team(TEAM,URL) VALUES ('Getafe CF','https://fc25-club-packs.ea.com/uploads/gaziantep/emblem/gaziantep.png');
INSERT INTO team(TEAM,URL) VALUES ('Gil Vicente','https://content.sportslogos.net/logos/128/3994/thumbs/luoxh8kjedoif2nyerzxiu00w.gif');
INSERT INTO team(TEAM,URL) VALUES ('Gillingham','https://content.sportslogos.net/logos/130/4025/thumbs/wyjvrxyhwca77k3fzef8nc957.gif');
INSERT INTO team(TEAM,URL) VALUES ('Gimcheon Sangmu','https://content.sportslogos.net/logos/179/5336/thumbs/533636530.gif');
INSERT INTO team(TEAM,URL) VALUES ('Gimnasia','https://content.sportslogos.net/logos/129/4049/thumbs/ntzfhqq4bo4jtheyww8gd3hco.gif');
INSERT INTO team(TEAM,URL) VALUES ('Girona FC','https://fc25-club-packs.ea.com/uploads/gimcheon-sangmu/emblem/gimcheon-sangmu.png');
INSERT INTO team(TEAM,URL) VALUES ('Glasgow City FC','https://fc25-club-packs.ea.com/uploads/gimnasia/emblem/gimnasia.png');
INSERT INTO team(TEAM,URL) VALUES ('Go Ahead Eagles','https://content.sportslogos.net/logos/146/4521/thumbs/43xatrl3h5fhgyetee4hutt9e.gif');
INSERT INTO team(TEAM,URL) VALUES ('Godoy Cruz','https://content.sportslogos.net/logos/141/5884/thumbs/588471792014.gif');
INSERT INTO team(TEAM,URL) VALUES ('Granada CF','https://content.sportslogos.net/logos/180/5356/thumbs/535655060.gif');
INSERT INTO team(TEAM,URL) VALUES ('Grazer AK','https://fc25-club-packs.ea.com/uploads/godoy-cruz/emblem/godoy-cruz.png');
INSERT INTO team(TEAM,URL) VALUES ('Grenoble Foot 38','https://fc25-club-packs.ea.com/uploads/g-rnik-zabrze/emblem/g-rnik-zabrze.png');
INSERT INTO team(TEAM,URL) VALUES ('Grimsby Town','https://fc25-club-packs.ea.com/uploads/g-ztepe/emblem/g-ztepe.png');
INSERT INTO team(TEAM,URL) VALUES ('Guaraní','https://content.sportslogos.net/logos/130/4038/thumbs/ncsc08uk8ivt8gicuf6n130ug.gif');
INSERT INTO team(TEAM,URL) VALUES ('GwangJu FC','https://fc25-club-packs.ea.com/uploads/grazer-ak/emblem/grazer-ak.png');
INSERT INTO team(TEAM,URL) VALUES ('Górnik Zabrze','https://content.sportslogos.net/logos/129/4056/thumbs/s4306yf50ihzfsfaxkudfnijh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Göztepe','https://fc25-club-packs.ea.com/uploads/grimsby-town/emblem/grimsby-town.png');
INSERT INTO team(TEAM,URL) VALUES ('HJK Helsinki','https://fc25-club-packs.ea.com/uploads/guaran/emblem/guaran.png');
INSERT INTO team(TEAM,URL) VALUES ('Hajduk Split','https://content.sportslogos.net/logos/151/4617/thumbs/lceehbjvqhjw8gj8htrb72ezi.gif');
INSERT INTO team(TEAM,URL) VALUES ('Halmstads BK','https://fc25-club-packs.ea.com/uploads/hjk-helsinki/emblem/hjk-helsinki.png');
INSERT INTO team(TEAM,URL) VALUES ('HamKam Fotball','https://content.sportslogos.net/logos/144/4470/thumbs/87m3j71s0itpzqaes48g60gjg.gif');
INSERT INTO team(TEAM,URL) VALUES ('Hamburger SV','https://fc25-club-packs.ea.com/uploads/halmstads-bk/emblem/halmstads-bk.png');
INSERT INTO team(TEAM,URL) VALUES ('Hammarby IF','https://fc25-club-packs.ea.com/uploads/hamkam-fotball/emblem/hamkam-fotball.png');
INSERT INTO team(TEAM,URL) VALUES ('Hannover 96','https://content.sportslogos.net/logos/132/4074/thumbs/tahrali7e0oqchvpnvg7bgas6.gif');
INSERT INTO team(TEAM,URL) VALUES ('Hannover 96 II','https://content.sportslogos.net/logos/136/4302/thumbs/yyfrifhfdrwwhqhe6hqzygx1h.gif');
INSERT INTO team(TEAM,URL) VALUES ('Harrogate Town','https://content.sportslogos.net/logos/132/4166/thumbs/f1u93gizvy909um2967cx8oyh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Hatayspor','https://content.sportslogos.net/logos/132/4166/thumbs/f1u93gizvy909um2967cx8oyh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Havre AC','https://fc25-club-packs.ea.com/uploads/harrogate-town/emblem/harrogate-town.png');
INSERT INTO team(TEAM,URL) VALUES ('Hearts','https://fc25-club-packs.ea.com/uploads/hatayspor/emblem/hatayspor.png');
INSERT INTO team(TEAM,URL) VALUES ('Heidenheim','https://fc25-club-packs.ea.com/uploads/havre-ac/emblem/havre-ac.png');
INSERT INTO team(TEAM,URL) VALUES ('Hellas Verona','https://fc25-club-packs.ea.com/uploads/hearts/emblem/hearts.png');
INSERT INTO team(TEAM,URL) VALUES ('Henan FC','https://fc25-club-packs.ea.com/uploads/heidenheim/emblem/heidenheim.png');
INSERT INTO team(TEAM,URL) VALUES ('Heracles Almelo','https://content.sportslogos.net/logos/128/4013/thumbs/f9ctcqmk5a2nlunkp3jfqdvlu.gif');
INSERT INTO team(TEAM,URL) VALUES ('Hertha BSC','https://content.sportslogos.net/logos/124/6724/thumbs/672491112018.gif');
INSERT INTO team(TEAM,URL) VALUES ('Hibernian','https://content.sportslogos.net/logos/180/5359/thumbs/535981010.gif');
INSERT INTO team(TEAM,URL) VALUES ('Holstein Kiel','https://content.sportslogos.net/logos/132/4071/thumbs/07cm1ieo1tilufl9krfga9p9p.gif');
INSERT INTO team(TEAM,URL) VALUES ('Houston Dash','https://content.sportslogos.net/logos/146/4510/thumbs/qomw59g1yj1u7i5he68mlitgk.gif');
INSERT INTO team(TEAM,URL) VALUES ('Houston Dynamo','https://fc25-club-packs.ea.com/uploads/holstein-kiel/emblem/holstein-kiel.png');
INSERT INTO team(TEAM,URL) VALUES ('Huachipato','https://content.sportslogos.net/logos/202/5864/thumbs/586475942021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Huddersfield','https://content.sportslogos.net/logos/9/1482/thumbs/148237592021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Hull City','https://fc25-club-packs.ea.com/uploads/huachipato/emblem/huachipato.png');
INSERT INTO team(TEAM,URL) VALUES ('Huracán','https://fc25-club-packs.ea.com/uploads/huddersfield/emblem/huddersfield.png');
INSERT INTO team(TEAM,URL) VALUES ('Hyderabad FC','https://content.sportslogos.net/logos/141/5884/thumbs/588471792014.gif');
INSERT INTO team(TEAM,URL) VALUES ('IDV','https://fc25-club-packs.ea.com/uploads/hurac-n/emblem/hurac-n.png');
INSERT INTO team(TEAM,URL) VALUES ('IF Elfsborg','https://fc25-club-packs.ea.com/uploads/hyderabad-fc/emblem/hyderabad-fc.png');
INSERT INTO team(TEAM,URL) VALUES ('IFK Göteborg','https://fc25-club-packs.ea.com/uploads/idv/emblem/idv.png');
INSERT INTO team(TEAM,URL) VALUES ('IFK Norrköping','https://content.sportslogos.net/logos/136/4296/thumbs/qtgu7c9kh6faq183fos8x1vzi.gif');
INSERT INTO team(TEAM,URL) VALUES ('IFK Värnamo','https://content.sportslogos.net/logos/136/4299/thumbs/efghu9oeh3ephhs5euffdie2n.gif');
INSERT INTO team(TEAM,URL) VALUES ('IK Sirius','https://content.sportslogos.net/logos/136/4305/thumbs/vrabfl3vg5yeoz4usvg999o0o.gif');
INSERT INTO team(TEAM,URL) VALUES ('Incheon United','https://content.sportslogos.net/logos/161/4919/thumbs/491997990.gif');
INSERT INTO team(TEAM,URL) VALUES ('Ind. Rivadavia','https://fc25-club-packs.ea.com/uploads/ik-sirius/emblem/ik-sirius.png');
INSERT INTO team(TEAM,URL) VALUES ('Indep. Medellín','https://content.sportslogos.net/logos/151/4603/thumbs/bn0xi6u8f1urlpf8e5tcikg8z.gif');
INSERT INTO team(TEAM,URL) VALUES ('Independiente','https://fc25-club-packs.ea.com/uploads/ind-rivadavia/emblem/ind-rivadavia.png');
INSERT INTO team(TEAM,URL) VALUES ('Instituto','https://fc25-club-packs.ea.com/uploads/indep-medell-n/emblem/indep-medell-n.png');
INSERT INTO team(TEAM,URL) VALUES ('Inter Miami CF','https://content.sportslogos.net/logos/124/5643/thumbs/564397552015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Inter Milan','https://fc25-club-packs.ea.com/uploads/instituto/emblem/instituto.png');
INSERT INTO team(TEAM,URL) VALUES ('Ipswich','https://content.sportslogos.net/logos/9/6621/thumbs/inter_miami_cf_logo_primary_2020sportslogosnet2103.gif');
INSERT INTO team(TEAM,URL) VALUES ('Jagiellonia','https://content.sportslogos.net/logos/128/3993/thumbs/cl833mzfmzejrwq7prvbzugm8.gif');
INSERT INTO team(TEAM,URL) VALUES ('Jahn Regensburg','https://fc25-club-packs.ea.com/uploads/ipswich/emblem/ipswich.png');
INSERT INTO team(TEAM,URL) VALUES ('Jamshedpur FC','https://fc25-club-packs.ea.com/uploads/jagiellonia/emblem/jagiellonia.png');
INSERT INTO team(TEAM,URL) VALUES ('Jeju United','https://fc25-club-packs.ea.com/uploads/jahn-regensburg/emblem/jahn-regensburg.png');
INSERT INTO team(TEAM,URL) VALUES ('Jeonbuk Hyundai','https://fc25-club-packs.ea.com/uploads/jamshedpur-fc/emblem/jamshedpur-fc.png');
INSERT INTO team(TEAM,URL) VALUES ('Junior','https://content.sportslogos.net/logos/151/4623/thumbs/fy2lzfqehwo0cnubenp8hg7om.gif');
INSERT INTO team(TEAM,URL) VALUES ('Juventus','https://content.sportslogos.net/logos/151/4619/thumbs/fykerzwg3jeh1cpfxvwpfho61.gif');
INSERT INTO team(TEAM,URL) VALUES ('K. Beerschot VA','https://content.sportslogos.net/logos/133/4188/thumbs/teg1hporjgd5qp70eaz16p5n7.gif');
INSERT INTO team(TEAM,URL) VALUES ('KAA Gent','https://content.sportslogos.net/logos/128/3997/thumbs/399744882017.gif');
INSERT INTO team(TEAM,URL) VALUES ('KC Current','https://fc25-club-packs.ea.com/uploads/k-beerschot-va/emblem/k-beerschot-va.png');
INSERT INTO team(TEAM,URL) VALUES ('KFUM-Kameratene','https://fc25-club-packs.ea.com/uploads/kaa-gent/emblem/kaa-gent.png');
INSERT INTO team(TEAM,URL) VALUES ('KRC Genk','https://fc25-club-packs.ea.com/uploads/kc-current/emblem/kc-current.png');
INSERT INTO team(TEAM,URL) VALUES ('KV Kortrijk','https://fc25-club-packs.ea.com/uploads/kfum-kameratene/emblem/kfum-kameratene.png');
INSERT INTO team(TEAM,URL) VALUES ('KV Mechelen','https://content.sportslogos.net/logos/129/4058/thumbs/e547f0ce55e7zgfjiev75c56f.gif');
INSERT INTO team(TEAM,URL) VALUES ('KVC Westerlo','https://fc25-club-packs.ea.com/uploads/kv-kortrijk/emblem/kv-kortrijk.png');
INSERT INTO team(TEAM,URL) VALUES ('Kaiserslautern','https://fc25-club-packs.ea.com/uploads/kv-mechelen/emblem/kv-mechelen.png');
INSERT INTO team(TEAM,URL) VALUES ('Kalmar FF','https://fc25-club-packs.ea.com/uploads/kvc-westerlo/emblem/kvc-westerlo.png');
INSERT INTO team(TEAM,URL) VALUES ('Karlsruher SC','https://fc25-club-packs.ea.com/uploads/kaiserslautern/emblem/kaiserslautern.png');
INSERT INTO team(TEAM,URL) VALUES ('Kasımpaşa','https://content.sportslogos.net/logos/136/4302/thumbs/yyfrifhfdrwwhqhe6hqzygx1h.gif');
INSERT INTO team(TEAM,URL) VALUES ('Kayserispor','https://fc25-club-packs.ea.com/uploads/karlsruher-sc/emblem/karlsruher-sc.png');
INSERT INTO team(TEAM,URL) VALUES ('Kerala Blasters','https://fc25-club-packs.ea.com/uploads/kas-mpa-a/emblem/kas-mpa-a.png');
INSERT INTO team(TEAM,URL) VALUES ('Kilmarnock','https://fc25-club-packs.ea.com/uploads/kayserispor/emblem/kayserispor.png');
INSERT INTO team(TEAM,URL) VALUES ('Konyaspor','https://fc25-club-packs.ea.com/uploads/kerala-blasters/emblem/kerala-blasters.png');
INSERT INTO team(TEAM,URL) VALUES ('Korona Kielce','https://content.sportslogos.net/logos/146/4512/thumbs/8ysnjgxrshpdh21ic05oyzwdc.gif');
INSERT INTO team(TEAM,URL) VALUES ('Kristiansund BK','https://content.sportslogos.net/logos/131/4153/thumbs/tlrhsdeld6efv0fb61xfpjsef.gif');
INSERT INTO team(TEAM,URL) VALUES ('LA Galaxy','https://fc25-club-packs.ea.com/uploads/korona-kielce/emblem/korona-kielce.png');
INSERT INTO team(TEAM,URL) VALUES ('LAFC','https://fc25-club-packs.ea.com/uploads/kristiansund-bk/emblem/kristiansund-bk.png');
INSERT INTO team(TEAM,URL) VALUES ('LASK','https://content.sportslogos.net/logos/124/5220/thumbs/522099052014.gif');
INSERT INTO team(TEAM,URL) VALUES ('LDU Quito','https://content.sportslogos.net/logos/141/5584/thumbs/558433762013.gif');
INSERT INTO team(TEAM,URL) VALUES ('LOSC Lille','https://fc25-club-packs.ea.com/uploads/lask/emblem/lask.png');
INSERT INTO team(TEAM,URL) VALUES ('Lanús','https://content.sportslogos.net/logos/133/4201/thumbs/g8auf2g9a7c7gjuqyml5fchp5.gif');
INSERT INTO team(TEAM,URL) VALUES ('Latium','https://content.sportslogos.net/logos/129/4051/thumbs/gqei1nfowihpqrnqgpifdnn2l.gif');
INSERT INTO team(TEAM,URL) VALUES ('Lausanne-Sport','https://content.sportslogos.net/logos/133/4200/thumbs/htcwhe6ghf1hjeq8skd58g1ld.gif');
INSERT INTO team(TEAM,URL) VALUES ('Laval MFC','https://en.wikipedia.org/wiki/SS_Lazio#/media/File:S.S._Lazio_badge.svg');
INSERT INTO team(TEAM,URL) VALUES ('Lecce','https://fc25-club-packs.ea.com/uploads/lausanne-sport/emblem/lausanne-sport.png');
INSERT INTO team(TEAM,URL) VALUES ('Lech Poznań','https://content.sportslogos.net/logos/231/6716/thumbs/671697262019.gif');
INSERT INTO team(TEAM,URL) VALUES ('Lechia Gdańsk','https://content.sportslogos.net/logos/128/4169/thumbs/0vlk100lc0ge7spztabghd361.gif');
INSERT INTO team(TEAM,URL) VALUES ('Leeds United','https://content.sportslogos.net/logos/131/4130/thumbs/6sf4i00c9ubg8ptf7rzhbher6.gif');
INSERT INTO team(TEAM,URL) VALUES ('Legia Warszawa','https://content.sportslogos.net/logos/129/4050/thumbs/bdmhq6439qs0oz0csqgfggmvp.gif');
INSERT INTO team(TEAM,URL) VALUES ('Leicester City','https://content.sportslogos.net/logos/125/6483/thumbs/648362882017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Levante Badalona','https://fc25-club-packs.ea.com/uploads/legia-warszawa/emblem/legia-warszawa.png');
INSERT INTO team(TEAM,URL) VALUES ('Levante UD','https://fc25-club-packs.ea.com/uploads/leicester-city/emblem/leicester-city.png');
INSERT INTO team(TEAM,URL) VALUES ('Leverkusen','https://content.sportslogos.net/logos/130/4026/thumbs/8ffugy3n51g0ihe8g55yrakmq.gif');
INSERT INTO team(TEAM,URL) VALUES ('Leyton Orient','https://content.sportslogos.net/logos/130/4026/thumbs/8ffugy3n51g0ihe8g55yrakmq.gif');
INSERT INTO team(TEAM,URL) VALUES ('Libertad','https://content.sportslogos.net/logos/132/4073/thumbs/kwoonkgpplfjq6wf98gk8ff8f.gif');
INSERT INTO team(TEAM,URL) VALUES ('Lillestrøm SK','https://fc25-club-packs.ea.com/uploads/leyton-orient/emblem/leyton-orient.png');
INSERT INTO team(TEAM,URL) VALUES ('Lincoln City','https://fc25-club-packs.ea.com/uploads/libertad/emblem/libertad.png');
INSERT INTO team(TEAM,URL) VALUES ('Liverpool','https://fc25-club-packs.ea.com/uploads/lillestr-m-sk/emblem/lillestr-m-sk.png');
INSERT INTO team(TEAM,URL) VALUES ('Luton Town','https://content.sportslogos.net/logos/141/5967/thumbs/596760672014.gif');
INSERT INTO team(TEAM,URL) VALUES ('Lyngby BK','https://content.sportslogos.net/logos/141/5885/thumbs/588510592013.gif');
INSERT INTO team(TEAM,URL) VALUES ('M''gladbach','https://fc25-club-packs.ea.com/uploads/luton-town/emblem/luton-town.png');
INSERT INTO team(TEAM,URL) VALUES ('MK Dons','https://fc25-club-packs.ea.com/uploads/lyngby-bk/emblem/lyngby-bk.png');
INSERT INTO team(TEAM,URL) VALUES ('Macarthur FC','https://fc25-club-packs.ea.com/uploads/m-gladbach/emblem/m-gladbach.png');
INSERT INTO team(TEAM,URL) VALUES ('Madrid CFF','https://fc25-club-packs.ea.com/uploads/mk-dons/emblem/mk-dons.png');
INSERT INTO team(TEAM,URL) VALUES ('Malmö FF','https://fc25-club-packs.ea.com/uploads/macarthur-fc/emblem/macarthur-fc.png');
INSERT INTO team(TEAM,URL) VALUES ('Man Utd','https://fc25-club-packs.ea.com/uploads/madrid-cff/emblem/madrid-cff.png');
INSERT INTO team(TEAM,URL) VALUES ('Manchester City','https://content.sportslogos.net/logos/130/4018/thumbs/hrhzmgl1gxoshl08h665ljjmh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Manchester Utd','https://content.sportslogos.net/logos/136/4303/thumbs/clexne95r9bkfsrxhg307ogf5.gif');
INSERT INTO team(TEAM,URL) VALUES ('Mansfield Town','https://en.wikipedia.org/wiki/Manchester_United_F.C.#/media/File:Manchester_United_FC_crest.svg');
INSERT INTO team(TEAM,URL) VALUES ('Mantova','https://fc25-club-packs.ea.com/uploads/manchester-city/emblem/manchester-city.png');
INSERT INTO team(TEAM,URL) VALUES ('Meizhou Hakka FC','https://fc25-club-packs.ea.com/uploads/manchester-utd/emblem/manchester-utd.png');
INSERT INTO team(TEAM,URL) VALUES ('Melb. Victory','https://fc25-club-packs.ea.com/uploads/mansfield-town/emblem/mansfield-town.png');
INSERT INTO team(TEAM,URL) VALUES ('Melbourne City','https://content.sportslogos.net/logos/133/4206/thumbs/m83q3qgkhlfzg1cxjd3ofi9f2.gif');
INSERT INTO team(TEAM,URL) VALUES ('Metropolitanos','https://fc25-club-packs.ea.com/uploads/meizhou-hakka-fc/emblem/meizhou-hakka-fc.png');
INSERT INTO team(TEAM,URL) VALUES ('Middlesbrough','https://content.sportslogos.net/logos/138/4337/thumbs/mn2lzo745oz7uyh26jx1jdmds.gif');
INSERT INTO team(TEAM,URL) VALUES ('Milano FC','https://content.sportslogos.net/logos/138/5762/thumbs/576230002015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Millonarios','https://content.sportslogos.net/logos/9/326/thumbs/1560.gif');
INSERT INTO team(TEAM,URL) VALUES ('Millwall','https://fc25-club-packs.ea.com/uploads/middlesbrough/emblem/middlesbrough.png');
INSERT INTO team(TEAM,URL) VALUES ('Minnesota United','https://content.sportslogos.net/logos/128/3992/thumbs/nwfgf6g3d2ut2c2q2sopm6sje.gif');
INSERT INTO team(TEAM,URL) VALUES ('Mjällby AIF','https://fc25-club-packs.ea.com/uploads/millonarios/emblem/millonarios.png');
INSERT INTO team(TEAM,URL) VALUES ('Modena','https://fc25-club-packs.ea.com/uploads/millwall/emblem/millwall.png');
INSERT INTO team(TEAM,URL) VALUES ('Mohammedan SC','https://content.sportslogos.net/logos/101/4975/thumbs/497562832013.gif');
INSERT INTO team(TEAM,URL) VALUES ('Mohun Bagan SG','https://content.sportslogos.net/logos/136/4304/thumbs/w9rvpgftvkxb995zpu8ppvf8w.gif');
INSERT INTO team(TEAM,URL) VALUES ('Molde FK','https://content.sportslogos.net/logos/134/4223/thumbs/egzgeqdkiasyg8r9sq266nwby.gif');
INSERT INTO team(TEAM,URL) VALUES ('Montpellier','https://fc25-club-packs.ea.com/uploads/mohammedan-sc/emblem/mohammedan-sc.png');
INSERT INTO team(TEAM,URL) VALUES ('Monza','https://fc25-club-packs.ea.com/uploads/mohun-bagan-sg/emblem/mohun-bagan-sg.png');
INSERT INTO team(TEAM,URL) VALUES ('Morecambe','https://fc25-club-packs.ea.com/uploads/molde-fk/emblem/molde-fk.png');
INSERT INTO team(TEAM,URL) VALUES ('Moreirense FC','https://content.sportslogos.net/logos/129/4052/thumbs/cmo65k4qo74nlhjxoq1ooh4fh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Motherwell','https://fc25-club-packs.ea.com/uploads/monza/emblem/monza.png');
INSERT INTO team(TEAM,URL) VALUES ('Motor Lublin','https://content.sportslogos.net/logos/134/4223/thumbs/egzgeqdkiasyg8r9sq266nwby.gif');
INSERT INTO team(TEAM,URL) VALUES ('Mumbai City FC','https://content.sportslogos.net/logos/179/5338/thumbs/533849420.gif');
INSERT INTO team(TEAM,URL) VALUES ('Málaga CF','https://content.sportslogos.net/logos/146/4513/thumbs/1kahcedeeorg9vh9v86mhhgly.gif');
INSERT INTO team(TEAM,URL) VALUES ('N.E.C. Nijmegen','https://fc25-club-packs.ea.com/uploads/motor-lublin/emblem/motor-lublin.png');
INSERT INTO team(TEAM,URL) VALUES ('NAC Breda','https://content.sportslogos.net/logos/141/5958/thumbs/595867362016.gif');
INSERT INTO team(TEAM,URL) VALUES ('NC Courage','https://content.sportslogos.net/logos/180/5360/thumbs/536085660.gif');
INSERT INTO team(TEAM,URL) VALUES ('NJ/NY Gotham','https://content.sportslogos.net/logos/180/5373/thumbs/537342560.gif');
INSERT INTO team(TEAM,URL) VALUES ('Nacional','https://content.sportslogos.net/logos/202/6455/thumbs/645532442017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Nacional Potosí','https://content.sportslogos.net/logos/202/6767/thumbs/676746082021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Nantong Zhiyun FC','https://content.sportslogos.net/logos/133/4202/thumbs/heb32d2tb5drp9pytmt5am6sh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Nashville SC','https://content.sportslogos.net/logos/133/4202/thumbs/heb32d2tb5drp9pytmt5am6sh.gif');
INSERT INTO team(TEAM,URL) VALUES ('New United Kingdom','https://content.sportslogos.net/logos/152/4657/thumbs/bq28h231f27bgb55lgivu8cdj.gif');
INSERT INTO team(TEAM,URL) VALUES ('New York City FC','https://content.sportslogos.net/logos/124/6506/thumbs/650624602018.gif');
INSERT INTO team(TEAM,URL) VALUES ('Newcastle Jets','https://fc25-club-packs.ea.com/uploads/new-united-kingdom/emblem/new-united-kingdom.png');
INSERT INTO team(TEAM,URL) VALUES ('Newcastle Utd','https://content.sportslogos.net/logos/9/5119/thumbs/511960002015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Newell''s','https://content.sportslogos.net/logos/138/4338/thumbs/7on0rifkpodzlfle3fl18cdm3.gif');
INSERT INTO team(TEAM,URL) VALUES ('Newport County','https://content.sportslogos.net/logos/138/4338/thumbs/7on0rifkpodzlfle3fl18cdm3.gif');
INSERT INTO team(TEAM,URL) VALUES ('NorthEast United','https://fc25-club-packs.ea.com/uploads/newell-s/emblem/newell-s.png');
INSERT INTO team(TEAM,URL) VALUES ('Northampton','https://content.sportslogos.net/logos/141/5948/thumbs/594821512016.gif');
INSERT INTO team(TEAM,URL) VALUES ('Norwich','https://content.sportslogos.net/logos/231/6801/thumbs/680145682021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Nott''m Forest','https://fc25-club-packs.ea.com/uploads/northampton/emblem/northampton.png');
INSERT INTO team(TEAM,URL) VALUES ('Notts County','https://fc25-club-packs.ea.com/uploads/norwich/emblem/norwich.png');
INSERT INTO team(TEAM,URL) VALUES ('OGC Nice','https://fc25-club-packs.ea.com/uploads/nott-m-forest/emblem/nott-m-forest.png');
INSERT INTO team(TEAM,URL) VALUES ('OH Leuven','https://content.sportslogos.net/logos/146/4514/thumbs/tuhjyvthhs34bw33e0z2pgal5.gif');
INSERT INTO team(TEAM,URL) VALUES ('OL','https://content.sportslogos.net/logos/129/4053/thumbs/ms5rh4j609oqsc3tj9wto0l8k.gif');
INSERT INTO team(TEAM,URL) VALUES ('OM','https://fc25-club-packs.ea.com/uploads/oh-leuven/emblem/oh-leuven.png');
INSERT INTO team(TEAM,URL) VALUES ('Odds BK','https://en.wikipedia.org/wiki/Olympique_Lyonnais#/media/File:Olympique_Lyonnais_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('Odisha FC','https://fc25-club-packs.ea.com/uploads/om/emblem/om.png');
INSERT INTO team(TEAM,URL) VALUES ('Olimpia','https://content.sportslogos.net/logos/160/4908/thumbs/490893240.gif');
INSERT INTO team(TEAM,URL) VALUES ('Olympiacos FC','https://fc25-club-packs.ea.com/uploads/odisha-fc/emblem/odisha-fc.png');
INSERT INTO team(TEAM,URL) VALUES ('Orlando City','https://content.sportslogos.net/logos/131/4137/thumbs/61hzc8gf1pf4mf0fg092zf0ed.gif');
INSERT INTO team(TEAM,URL) VALUES ('Orlando Pride','https://content.sportslogos.net/logos/131/4137/thumbs/61hzc8gf1pf4mf0fg092zf0ed.gif');
INSERT INTO team(TEAM,URL) VALUES ('Oxford United','https://content.sportslogos.net/logos/124/5938/thumbs/593832902016.gif');
INSERT INTO team(TEAM,URL) VALUES ('PAOK FC','https://content.sportslogos.net/logos/202/5939/thumbs/593987032016.gif');
INSERT INTO team(TEAM,URL) VALUES ('PEC Zwolle','https://content.sportslogos.net/logos/231/6801/thumbs/680145682021.gif');
INSERT INTO team(TEAM,URL) VALUES ('PSV','https://content.sportslogos.net/logos/141/5584/thumbs/558433762013.gif');
INSERT INTO team(TEAM,URL) VALUES ('Palermo','https://content.sportslogos.net/logos/180/5357/thumbs/535725960.gif');
INSERT INTO team(TEAM,URL) VALUES ('Palestino','https://en.wikipedia.org/wiki/PSV_Eindhoven#/media/File:PSV_Eindhoven.svg');
INSERT INTO team(TEAM,URL) VALUES ('Panathinaikos','https://content.sportslogos.net/logos/128/4003/thumbs/xgokakbm18m4xmli7ztgymogo.gif');
INSERT INTO team(TEAM,URL) VALUES ('Paris FC','https://content.sportslogos.net/logos/128/4003/thumbs/xgokakbm18m4xmli7ztgymogo.gif');
INSERT INTO team(TEAM,URL) VALUES ('Paris SG','https://content.sportslogos.net/logos/131/4138/thumbs/hnepfceeodu2za5vvzcs19mtg.gif');
INSERT INTO team(TEAM,URL) VALUES ('Parma','https://content.sportslogos.net/logos/146/4525/thumbs/e4lw4y4mea088ckkbh0bn5bis.gif');
INSERT INTO team(TEAM,URL) VALUES ('Pau FC','https://content.sportslogos.net/logos/129/4159/thumbs/hzgunkh343rdlm9u1479ezime.gif');
INSERT INTO team(TEAM,URL) VALUES ('Perth Glory','https://content.sportslogos.net/logos/128/4002/thumbs/2pmj9op719we21egqmybehggs.gif');
INSERT INTO team(TEAM,URL) VALUES ('Peterborough','https://content.sportslogos.net/logos/151/4611/thumbs/fgz9pnoyyoh18awmhowy5ngt3.gif');
INSERT INTO team(TEAM,URL) VALUES ('Peñarol','https://content.sportslogos.net/logos/133/4204/thumbs/lxepgu7zs80pb6icebwxb9kpr.gif');
INSERT INTO team(TEAM,URL) VALUES ('Philadelphia','https://content.sportslogos.net/logos/138/4339/thumbs/zhkorlzhp6psdayakhu6lgbdb.gif');
INSERT INTO team(TEAM,URL) VALUES ('Piast Gliwice','https://fc25-club-packs.ea.com/uploads/peterborough/emblem/peterborough.png');
INSERT INTO team(TEAM,URL) VALUES ('Pisa','https://content.sportslogos.net/logos/203/5874/thumbs/587480742014.gif');
INSERT INTO team(TEAM,URL) VALUES ('Platense','https://fc25-club-packs.ea.com/uploads/piast-gliwice/emblem/piast-gliwice.png');
INSERT INTO team(TEAM,URL) VALUES ('Plymouth Argyle','https://fc25-club-packs.ea.com/uploads/pisa/emblem/pisa.png');
INSERT INTO team(TEAM,URL) VALUES ('Pogoń Szczecin','https://content.sportslogos.net/logos/179/5347/thumbs/534787530.gif');
INSERT INTO team(TEAM,URL) VALUES ('Pohang Steelers','https://fc25-club-packs.ea.com/uploads/plymouth-argyle/emblem/plymouth-argyle.png');
INSERT INTO team(TEAM,URL) VALUES ('Politehnica Ia?i','https://fc25-club-packs.ea.com/uploads/pogo-szczecin/emblem/pogo-szczecin.png');
INSERT INTO team(TEAM,URL) VALUES ('Port Vale','https://content.sportslogos.net/logos/151/4626/thumbs/2abpocfdb5wbrgebex3l4gy53.gif');
INSERT INTO team(TEAM,URL) VALUES ('Portland Thorns','https://fc25-club-packs.ea.com/uploads/politehnica-ia-i/emblem/politehnica-ia-i.png');
INSERT INTO team(TEAM,URL) VALUES ('Portland Timbers','https://fc25-club-packs.ea.com/uploads/port-vale/emblem/port-vale.png');
INSERT INTO team(TEAM,URL) VALUES ('Portsmouth','https://content.sportslogos.net/logos/202/5867/thumbs/586767482018.gif');
INSERT INTO team(TEAM,URL) VALUES ('Preston','https://content.sportslogos.net/logos/126/3917/thumbs/1zk2fqjjqmtysg1hqnxe9fyje.gif');
INSERT INTO team(TEAM,URL) VALUES ('Preußen Münster','https://fc25-club-packs.ea.com/uploads/portsmouth/emblem/portsmouth.png');
INSERT INTO team(TEAM,URL) VALUES ('Punjab FC','https://content.sportslogos.net/logos/125/6484/thumbs/648475962017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Puszcza','https://fc25-club-packs.ea.com/uploads/preu-en-m-nster/emblem/preu-en-m-nster.png');
INSERT INTO team(TEAM,URL) VALUES ('QPR','https://content.sportslogos.net/logos/134/4226/thumbs/o55wh908e4eev7fnd8edn3nkq.gif');
INSERT INTO team(TEAM,URL) VALUES ('Qarabağ FK','https://fc25-club-packs.ea.com/uploads/puszcza/emblem/puszcza.png');
INSERT INTO team(TEAM,URL) VALUES ('Qingdao Hainiu','https://fc25-club-packs.ea.com/uploads/qpr/emblem/qpr.png');
INSERT INTO team(TEAM,URL) VALUES ('Qingdao W. Coast','https://fc25-club-packs.ea.com/uploads/qaraba-fk/emblem/qaraba-fk.png');
INSERT INTO team(TEAM,URL) VALUES ('R. Oviedo','https://fc25-club-packs.ea.com/uploads/qingdao-hainiu/emblem/qingdao-hainiu.png');
INSERT INTO team(TEAM,URL) VALUES ('R. Racing Club','https://fc25-club-packs.ea.com/uploads/qingdao-w-coast/emblem/qingdao-w-coast.png');
INSERT INTO team(TEAM,URL) VALUES ('R. Sporting','https://fc25-club-packs.ea.com/uploads/r-oviedo/emblem/r-oviedo.png');
INSERT INTO team(TEAM,URL) VALUES ('R. Union St.-G.','https://fc25-club-packs.ea.com/uploads/r-racing-club/emblem/r-racing-club.png');
INSERT INTO team(TEAM,URL) VALUES ('R. Valladolid CF','https://content.sportslogos.net/logos/133/4199/thumbs/hkhfx27e6dyy297na8yhqryxj.gif');
INSERT INTO team(TEAM,URL) VALUES ('RB Leipzig','https://fc25-club-packs.ea.com/uploads/r-union-st-g/emblem/r-union-st-g.png');
INSERT INTO team(TEAM,URL) VALUES ('RB Salzburg','https://content.sportslogos.net/logos/130/4032/thumbs/3histfa5a660fjnvkxgu8qv0o.gif');
INSERT INTO team(TEAM,URL) VALUES ('RC Celta','https://fc25-club-packs.ea.com/uploads/rb-leipzig/emblem/rb-leipzig.png');
INSERT INTO team(TEAM,URL) VALUES ('RC Deportivo','https://content.sportslogos.net/logos/131/4144/thumbs/fgska7m9ialr2uxoxnxtbbhee.gif');
INSERT INTO team(TEAM,URL) VALUES ('RC Lens','https://fc25-club-packs.ea.com/uploads/rc-celta/emblem/rc-celta.png');
INSERT INTO team(TEAM,URL) VALUES ('RCD Espanyol','https://content.sportslogos.net/logos/179/5342/thumbs/534228680.gif');
INSERT INTO team(TEAM,URL) VALUES ('RCD Mallorca','https://content.sportslogos.net/logos/129/4058/thumbs/e547f0ce55e7zgfjiev75c56f.gif');
INSERT INTO team(TEAM,URL) VALUES ('RKC Waalwijk','https://fc25-club-packs.ea.com/uploads/rcd-espanyol/emblem/rcd-espanyol.png');
INSERT INTO team(TEAM,URL) VALUES ('RSC Anderlecht','https://content.sportslogos.net/logos/130/4030/thumbs/eq6wo9tjo6ogehuaph3koploa.gif');
INSERT INTO team(TEAM,URL) VALUES ('Rac. Louisville','https://content.sportslogos.net/logos/180/5361/thumbs/536167160.gif');
INSERT INTO team(TEAM,URL) VALUES ('Racing Club','https://content.sportslogos.net/logos/131/4095/thumbs/yyteuzhggggmb4euq9z2cpz79.gif');
INSERT INTO team(TEAM,URL) VALUES ('Racing de Ferrol','https://content.sportslogos.net/logos/202/6770/thumbs/677079002021.gif');
INSERT INTO team(TEAM,URL) VALUES ('Radomiak Radom','https://content.sportslogos.net/logos/131/4141/thumbs/9h5jh6uyoqjvaf3fwiv1veokc.gif');
INSERT INTO team(TEAM,URL) VALUES ('Raków','https://fc25-club-packs.ea.com/uploads/racing-de-ferrol/emblem/racing-de-ferrol.png');
INSERT INTO team(TEAM,URL) VALUES ('Randers FC','https://fc25-club-packs.ea.com/uploads/radomiak-radom/emblem/radomiak-radom.png');
INSERT INTO team(TEAM,URL) VALUES ('Rangers','https://fc25-club-packs.ea.com/uploads/rak-w/emblem/rak-w.png');
INSERT INTO team(TEAM,URL) VALUES ('Rayo Vallecano','https://content.sportslogos.net/logos/160/4909/thumbs/490993032003.gif');
INSERT INTO team(TEAM,URL) VALUES ('Rayo Zuliano','https://content.sportslogos.net/logos/146/4525/thumbs/e4lw4y4mea088ckkbh0bn5bis.gif');
INSERT INTO team(TEAM,URL) VALUES ('Reading','https://content.sportslogos.net/logos/130/4029/thumbs/edkhmdzejzfrvchzv4gf97ska.gif');
INSERT INTO team(TEAM,URL) VALUES ('Real Betis','https://content.sportslogos.net/logos/130/4029/thumbs/edkhmdzejzfrvchzv4gf97ska.gif');
INSERT INTO team(TEAM,URL) VALUES ('Real Madrid','https://content.sportslogos.net/logos/125/3839/thumbs/f9e89p4vgghkfn1gelg3334rs.gif');
INSERT INTO team(TEAM,URL) VALUES ('Real Madrid CF','https://content.sportslogos.net/logos/130/4028/thumbs/x0e2fl7xk18oj7shbuf6t5nnp.gif');
INSERT INTO team(TEAM,URL) VALUES ('Real Salt Lake','https://content.sportslogos.net/logos/130/4017/thumbs/yfhezt5oyr0jbq29u4hp50w63.gif');
INSERT INTO team(TEAM,URL) VALUES ('Real Sociedad','https://content.sportslogos.net/logos/130/4017/thumbs/yfhezt5oyr0jbq29u4hp50w63.gif');
INSERT INTO team(TEAM,URL) VALUES ('Real Tomayapo','https://content.sportslogos.net/logos/9/394/thumbs/39489852010.gif');
INSERT INTO team(TEAM,URL) VALUES ('Real Zaragoza','https://content.sportslogos.net/logos/130/4031/thumbs/e8k432xe04mg17rb0hm7ykujl.gif');
INSERT INTO team(TEAM,URL) VALUES ('Red Bulls','https://content.sportslogos.net/logos/130/4033/thumbs/nmgy7yrx9i3r8xc58u8jjgh7b.gif');
INSERT INTO team(TEAM,URL) VALUES ('Red Star FC','https://content.sportslogos.net/logos/130/4033/thumbs/nmgy7yrx9i3r8xc58u8jjgh7b.gif');
INSERT INTO team(TEAM,URL) VALUES ('Reggiana','https://content.sportslogos.net/logos/9/1876/thumbs/i9ni847kriagxdlb7xewa6dl8.gif');
INSERT INTO team(TEAM,URL) VALUES ('Rio Ave FC','https://content.sportslogos.net/logos/141/5603/thumbs/560376742014.gif');
INSERT INTO team(TEAM,URL) VALUES ('River Plate','https://fc25-club-packs.ea.com/uploads/reggiana/emblem/reggiana.png');
INSERT INTO team(TEAM,URL) VALUES ('Rodez AF','https://content.sportslogos.net/logos/179/5343/thumbs/534353580.gif');
INSERT INTO team(TEAM,URL) VALUES ('Roma','https://content.sportslogos.net/logos/124/3811/thumbs/nz511shtsglwckrr925qeai2f.gif');
INSERT INTO team(TEAM,URL) VALUES ('Rongcheng FC','https://fc25-club-packs.ea.com/uploads/rodez-af/emblem/rodez-af.png');
INSERT INTO team(TEAM,URL) VALUES ('Rosario Central','https://content.sportslogos.net/logos/128/3996/thumbs/eezkjfmm1m7mmg9nm5t0075nh.gif');
INSERT INTO team(TEAM,URL) VALUES ('Rosenborg BK','https://content.sportslogos.net/logos/146/4525/thumbs/e4lw4y4mea088ckkbh0bn5bis.gif');
INSERT INTO team(TEAM,URL) VALUES ('Ross County','https://fc25-club-packs.ea.com/uploads/rosario-central/emblem/rosario-central.png');
INSERT INTO team(TEAM,URL) VALUES ('Rot-Weiss Essen','https://fc25-club-packs.ea.com/uploads/rosenborg-bk/emblem/rosenborg-bk.png');
INSERT INTO team(TEAM,URL) VALUES ('Rotherham Utd','https://content.sportslogos.net/logos/146/4514/thumbs/tuhjyvthhs34bw33e0z2pgal5.gif');
INSERT INTO team(TEAM,URL) VALUES ('Royal Antwerp FC','https://fc25-club-packs.ea.com/uploads/rot-weiss-essen/emblem/rot-weiss-essen.png');
INSERT INTO team(TEAM,URL) VALUES ('S. Ameliano','https://fc25-club-packs.ea.com/uploads/rotherham-utd/emblem/rotherham-utd.png');
INSERT INTO team(TEAM,URL) VALUES ('S. Trinidense','https://content.sportslogos.net/logos/146/4525/thumbs/e4lw4y4mea088ckkbh0bn5bis.gif');
INSERT INTO team(TEAM,URL) VALUES ('SC Bastia','https://fc25-club-packs.ea.com/uploads/s-ameliano/emblem/s-ameliano.png');
INSERT INTO team(TEAM,URL) VALUES ('SC Braga','https://fc25-club-packs.ea.com/uploads/s-trinidense/emblem/s-trinidense.png');
INSERT INTO team(TEAM,URL) VALUES ('SC Freiburg','https://content.sportslogos.net/logos/129/4057/thumbs/8n6ge9hk7kj35sf0w9fj1ci6g.gif');
INSERT INTO team(TEAM,URL) VALUES ('SC O?elul Gala?i','https://content.sportslogos.net/logos/129/4057/thumbs/8n6ge9hk7kj35sf0w9fj1ci6g.gif');
INSERT INTO team(TEAM,URL) VALUES ('SC Paderborn 07','https://content.sportslogos.net/logos/132/4080/thumbs/v4ymltyv9o5g7afvh3v0s7cwu.gif');
INSERT INTO team(TEAM,URL) VALUES ('SC Verl','https://fc25-club-packs.ea.com/uploads/sc-o-elul-gala-i/emblem/sc-o-elul-gala-i.png');
INSERT INTO team(TEAM,URL) VALUES ('SCR Altach','https://fc25-club-packs.ea.com/uploads/sc-paderborn-07/emblem/sc-paderborn-07.png');
INSERT INTO team(TEAM,URL) VALUES ('SD Eibar','https://fc25-club-packs.ea.com/uploads/sc-verl/emblem/sc-verl.png');
INSERT INTO team(TEAM,URL) VALUES ('SD Huesca','https://fc25-club-packs.ea.com/uploads/scr-altach/emblem/scr-altach.png');
INSERT INTO team(TEAM,URL) VALUES ('SGS Essen','https://fc25-club-packs.ea.com/uploads/sd-eibar/emblem/sd-eibar.png');
INSERT INTO team(TEAM,URL) VALUES ('SJ Earthquakes','https://fc25-club-packs.ea.com/uploads/sd-huesca/emblem/sd-huesca.png');
INSERT INTO team(TEAM,URL) VALUES ('SK Brann','https://fc25-club-packs.ea.com/uploads/sgs-essen/emblem/sgs-essen.png');
INSERT INTO team(TEAM,URL) VALUES ('SK Rapid','https://content.sportslogos.net/logos/52/1403/thumbs/6029.gif');
INSERT INTO team(TEAM,URL) VALUES ('SK Sturm Graz','https://fc25-club-packs.ea.com/uploads/sk-brann/emblem/sk-brann.png');
INSERT INTO team(TEAM,URL) VALUES ('SL Benfica','https://fc25-club-packs.ea.com/uploads/sk-rapid/emblem/sk-rapid.png');
INSERT INTO team(TEAM,URL) VALUES ('SM Caen','https://fc25-club-packs.ea.com/uploads/sk-sturm-graz/emblem/sk-sturm-graz.png');
INSERT INTO team(TEAM,URL) VALUES ('SS Juve Stabia','https://content.sportslogos.net/logos/179/5332/thumbs/533288680.gif');
INSERT INTO team(TEAM,URL) VALUES ('SSC Napoli','https://content.sportslogos.net/logos/129/4059/thumbs/sgzltueu2ie15k8s2lfsgi5mm.gif');
INSERT INTO team(TEAM,URL) VALUES ('SSV Ulm 1846','https://fc25-club-packs.ea.com/uploads/ss-juve-stabia/emblem/ss-juve-stabia.png');
INSERT INTO team(TEAM,URL) VALUES ('STVV','https://content.sportslogos.net/logos/128/3999/thumbs/ig0qxnu0hsyvb5eugex7k50uh.gif');
INSERT INTO team(TEAM,URL) VALUES ('SV Darmstadt 98','https://fc25-club-packs.ea.com/uploads/ssv-ulm-1846/emblem/ssv-ulm-1846.png');
INSERT INTO team(TEAM,URL) VALUES ('SV Elversberg','https://fc25-club-packs.ea.com/uploads/stvv/emblem/stvv.png');
INSERT INTO team(TEAM,URL) VALUES ('SV Sandhausen','https://fc25-club-packs.ea.com/uploads/sv-darmstadt-98/emblem/sv-darmstadt-98.png');
INSERT INTO team(TEAM,URL) VALUES ('SV Waldhof','https://fc25-club-packs.ea.com/uploads/sv-elversberg/emblem/sv-elversberg.png');
INSERT INTO team(TEAM,URL) VALUES ('SV Werder Bremen','https://content.sportslogos.net/logos/180/5372/thumbs/537217030.gif');
INSERT INTO team(TEAM,URL) VALUES ('SZ Peng City','https://fc25-club-packs.ea.com/uploads/sv-waldhof/emblem/sv-waldhof.png');
INSERT INTO team(TEAM,URL) VALUES ('Saarbrücken','https://content.sportslogos.net/logos/132/4085/thumbs/xx2xphrkj2iwuooysinxa8fiv.gif');
INSERT INTO team(TEAM,URL) VALUES ('Salernitana','https://fc25-club-packs.ea.com/uploads/sz-peng-city/emblem/sz-peng-city.png');
INSERT INTO team(TEAM,URL) VALUES ('Salford City','https://fc25-club-packs.ea.com/uploads/salernitana/emblem/salernitana.png');
INSERT INTO team(TEAM,URL) VALUES ('Sampdoria','https://fc25-club-packs.ea.com/uploads/salford-city/emblem/salford-city.png');
INSERT INTO team(TEAM,URL) VALUES ('Samsunspor','https://content.sportslogos.net/logos/128/4009/thumbs/4hzy4bpfcsjjuhtmd1pt0zmic.gif');
INSERT INTO team(TEAM,URL) VALUES ('San Diego Wave','https://content.sportslogos.net/logos/131/4147/thumbs/ozhvlj1zmricpsw2thwfgteov.gif');
INSERT INTO team(TEAM,URL) VALUES ('San Lorenzo','https://content.sportslogos.net/logos/52/1396/thumbs/bbax8sfofrfhze3qfixydulzq.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sandefjord','https://fc25-club-packs.ea.com/uploads/san-lorenzo/emblem/san-lorenzo.png');
INSERT INTO team(TEAM,URL) VALUES ('Santa Clara','https://fc25-club-packs.ea.com/uploads/sandefjord/emblem/sandefjord.png');
INSERT INTO team(TEAM,URL) VALUES ('Sarmiento','https://content.sportslogos.net/logos/141/4419/thumbs/441982882011.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sarpsborg 08','https://content.sportslogos.net/logos/133/4206/thumbs/m83q3qgkhlfzg1cxjd3ofi9f2.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sassuolo','https://fc25-club-packs.ea.com/uploads/sarpsborg-08/emblem/sarpsborg-08.png');
INSERT INTO team(TEAM,URL) VALUES ('Seattle Reign','https://content.sportslogos.net/logos/128/5870/thumbs/587053750.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sepsi OSK','https://content.sportslogos.net/logos/202/5863/thumbs/586371692013.gif');
INSERT INTO team(TEAM,URL) VALUES ('Servette FC','https://fc25-club-packs.ea.com/uploads/sepsi-osk/emblem/sepsi-osk.png');
INSERT INTO team(TEAM,URL) VALUES ('Sevilla FC','https://content.sportslogos.net/logos/146/4506/thumbs/a2g7begi3igu6727mksnapani.gif');
INSERT INTO team(TEAM,URL) VALUES ('Shakhtar Donetsk','https://content.sportslogos.net/logos/130/4034/thumbs/ce4732ploudlmfblce1rm3azn.gif');
INSERT INTO team(TEAM,URL) VALUES ('Shamrock Rovers','https://content.sportslogos.net/logos/140/4373/thumbs/9cph3phlcgnxqokjy5t0fgg4x.gif');
INSERT INTO team(TEAM,URL) VALUES ('Shandong Taishan','https://fc25-club-packs.ea.com/uploads/shamrock-rovers/emblem/shamrock-rovers.png');
INSERT INTO team(TEAM,URL) VALUES ('Shanghai Port FC','https://content.sportslogos.net/logos/152/4655/thumbs/p1ney3phvdh5shwg8q792csxo.gif');
INSERT INTO team(TEAM,URL) VALUES ('Shanghai Shenhua','https://content.sportslogos.net/logos/152/4656/thumbs/4hrzmlaunsfs2w80srd7tgn9b.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sheffield Utd','https://content.sportslogos.net/logos/152/4656/thumbs/4hrzmlaunsfs2w80srd7tgn9b.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sheffield Wed','https://content.sportslogos.net/logos/141/5905/thumbs/590513682014.gif');
INSERT INTO team(TEAM,URL) VALUES ('Shelbourne','https://fc25-club-packs.ea.com/uploads/sheffield-wed/emblem/sheffield-wed.png');
INSERT INTO team(TEAM,URL) VALUES ('Shrewsbury','https://content.sportslogos.net/logos/138/4336/thumbs/mhnl0k7zgwtc1c3z09cmcymer.gif');
INSERT INTO team(TEAM,URL) VALUES ('Silkeborg IF','https://fc25-club-packs.ea.com/uploads/shrewsbury/emblem/shrewsbury.png');
INSERT INTO team(TEAM,URL) VALUES ('Sivasspor','https://content.sportslogos.net/logos/160/4910/thumbs/491011350.gif');
INSERT INTO team(TEAM,URL) VALUES ('Slavia Praha','https://content.sportslogos.net/logos/131/4147/thumbs/ozhvlj1zmricpsw2thwfgteov.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sligo Rovers','https://fc25-club-packs.ea.com/uploads/slavia-praha/emblem/slavia-praha.png');
INSERT INTO team(TEAM,URL) VALUES ('Sounders FC','https://content.sportslogos.net/logos/125/6502/thumbs/650299812017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Southampton','https://content.sportslogos.net/logos/160/4911/thumbs/491134540.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sp. Charleroi','https://content.sportslogos.net/logos/160/4909/thumbs/490993032003.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sparta Praha','https://fc25-club-packs.ea.com/uploads/southampton/emblem/southampton.png');
INSERT INTO team(TEAM,URL) VALUES ('Sparta Rotterdam','https://content.sportslogos.net/logos/141/5590/thumbs/559033992013.gif');
INSERT INTO team(TEAM,URL) VALUES ('Spezia','https://content.sportslogos.net/logos/180/5365/thumbs/536595170.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sport Huancayo','https://content.sportslogos.net/logos/180/5365/thumbs/536595170.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sporting CP','https://content.sportslogos.net/logos/160/4901/thumbs/490199630.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sporting KC','https://fc25-club-packs.ea.com/uploads/sport-huancayo/emblem/sport-huancayo.png');
INSERT INTO team(TEAM,URL) VALUES ('Sportivo Luqueño','https://content.sportslogos.net/logos/130/4035/thumbs/oxvfl8qkheh3h0fatfp0ekhdd.gif');
INSERT INTO team(TEAM,URL) VALUES ('Spurs','https://content.sportslogos.net/logos/130/4035/thumbs/oxvfl8qkheh3h0fatfp0ekhdd.gif');
INSERT INTO team(TEAM,URL) VALUES ('St. Johnstone','https://fc25-club-packs.ea.com/uploads/sportivo-luque-o/emblem/sportivo-luque-o.png');
INSERT INTO team(TEAM,URL) VALUES ('St. Louis CITY SC','https://en.wikipedia.org/wiki/Tottenham_Hotspur_F.C.#/media/File:Tottenham_Hotspur.svg');
INSERT INTO team(TEAM,URL) VALUES ('St. Mirren','https://content.sportslogos.net/logos/146/4515/thumbs/teyt5v7yyxiqvi5juvbeh4zig.gif');
INSERT INTO team(TEAM,URL) VALUES ('St. Pats','https://content.sportslogos.net/logos/9/6742/thumbs/674230322023.gif');
INSERT INTO team(TEAM,URL) VALUES ('Stade Brestois 29','https://content.sportslogos.net/logos/146/4516/thumbs/9e4eh9og8eef1m1treooyuto7.gif');
INSERT INTO team(TEAM,URL) VALUES ('Stade Rennais FC','https://fc25-club-packs.ea.com/uploads/st-pats/emblem/st-pats.png');
INSERT INTO team(TEAM,URL) VALUES ('Stade de Reims','https://content.sportslogos.net/logos/129/4063/thumbs/p222ggtnekduljfpglyu61j5l.gif');
INSERT INTO team(TEAM,URL) VALUES ('Stal Mielec','https://content.sportslogos.net/logos/129/4060/thumbs/n24fu5g7tz5gagmjlx61pbww4.gif');
INSERT INTO team(TEAM,URL) VALUES ('Standard Liège','https://content.sportslogos.net/logos/129/4061/thumbs/6ebeb0v6plo16cuvizx8cedbf.gif');
INSERT INTO team(TEAM,URL) VALUES ('Stevenage','https://fc25-club-packs.ea.com/uploads/stal-mielec/emblem/stal-mielec.png');
INSERT INTO team(TEAM,URL) VALUES ('Stockport','https://content.sportslogos.net/logos/131/4151/thumbs/t5hlff3zax8ps38hnctupzclv.gif');
INSERT INTO team(TEAM,URL) VALUES ('Stoke City','https://fc25-club-packs.ea.com/uploads/stevenage/emblem/stevenage.png');
INSERT INTO team(TEAM,URL) VALUES ('Strasbourg','https://fc25-club-packs.ea.com/uploads/stockport/emblem/stockport.png');
INSERT INTO team(TEAM,URL) VALUES ('Strømsgodset IF','https://content.sportslogos.net/logos/52/1377/thumbs/hdd4efpf78qg631npfyr6ecnk.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sunderland','https://fc25-club-packs.ea.com/uploads/strasbourg/emblem/strasbourg.png');
INSERT INTO team(TEAM,URL) VALUES ('Suwon FC','https://fc25-club-packs.ea.com/uploads/str-msgodset-if/emblem/str-msgodset-if.png');
INSERT INTO team(TEAM,URL) VALUES ('Swansea City','https://en.wikipedia.org/wiki/FC_S%C3%BCdtirol#/media/File:FC_Sudtirol_crest.svg');
INSERT INTO team(TEAM,URL) VALUES ('Swindon Town','https://content.sportslogos.net/logos/160/4901/thumbs/490199630.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sydney FC','https://content.sportslogos.net/logos/203/5873/thumbs/587380602014.gif');
INSERT INTO team(TEAM,URL) VALUES ('Sønderjyske','https://content.sportslogos.net/logos/202/5866/thumbs/586611942013.gif');
INSERT INTO team(TEAM,URL) VALUES ('Südtirol','https://fc25-club-packs.ea.com/uploads/swindon-town/emblem/swindon-town.png');
INSERT INTO team(TEAM,URL) VALUES ('TSG Hoffenheim','https://content.sportslogos.net/logos/138/4340/thumbs/dnrje14s3vgpr04qiofdhho2z.gif');
INSERT INTO team(TEAM,URL) VALUES ('TSV Hartberg','https://content.sportslogos.net/logos/132/4167/thumbs/1rev8mqgfxi5v0ap8hp9nau0d.gif');
INSERT INTO team(TEAM,URL) VALUES ('Talleres','https://fc25-club-packs.ea.com/uploads/tsv-hartberg/emblem/tsv-hartberg.png');
INSERT INTO team(TEAM,URL) VALUES ('The Strongest','https://fc25-club-packs.ea.com/uploads/talleres/emblem/talleres.png');
INSERT INTO team(TEAM,URL) VALUES ('Tianjin JMT FC','https://fc25-club-packs.ea.com/uploads/the-strongest/emblem/the-strongest.png');
INSERT INTO team(TEAM,URL) VALUES ('Tigre','https://content.sportslogos.net/logos/152/4658/thumbs/hg8h2we25hutc6qa52a5f642j.gif');
INSERT INTO team(TEAM,URL) VALUES ('Torino','https://content.sportslogos.net/logos/134/4231/thumbs/h8rbicljun6g9t74rtai0sh1j.gif');
INSERT INTO team(TEAM,URL) VALUES ('Toronto FC','https://content.sportslogos.net/logos/128/3998/thumbs/rdgcmhe9zcjh5tuwbu8s0sea4.gif');
INSERT INTO team(TEAM,URL) VALUES ('Toulouse FC','https://content.sportslogos.net/logos/9/1249/thumbs/124929902010.gif');
INSERT INTO team(TEAM,URL) VALUES ('Trabzonspor','https://content.sportslogos.net/logos/129/4064/thumbs/7shszng326awpet96flvcy848.gif');
INSERT INTO team(TEAM,URL) VALUES ('Tranmere Rovers','https://content.sportslogos.net/logos/131/4153/thumbs/tlrhsdeld6efv0fb61xfpjsef.gif');
INSERT INTO team(TEAM,URL) VALUES ('Tromsø IL','https://fc25-club-packs.ea.com/uploads/tranmere-rovers/emblem/tranmere-rovers.png');
INSERT INTO team(TEAM,URL) VALUES ('Turbine Potsdam','https://fc25-club-packs.ea.com/uploads/troms-il/emblem/troms-il.png');
INSERT INTO team(TEAM,URL) VALUES ('Técnico U.','https://fc25-club-packs.ea.com/uploads/turbine-potsdam/emblem/turbine-potsdam.png');
INSERT INTO team(TEAM,URL) VALUES ('U. Católica','https://fc25-club-packs.ea.com/uploads/t-cnico-u/emblem/t-cnico-u.png');
INSERT INTO team(TEAM,URL) VALUES ('UCV','https://fc25-club-packs.ea.com/uploads/ucv/emblem/ucv.png');
INSERT INTO team(TEAM,URL) VALUES ('UD Almería','https://content.sportslogos.net/logos/52/1427/thumbs/kn4kqvkd5gvtuk5bkbcua80em.gif');
INSERT INTO team(TEAM,URL) VALUES ('UD Las Palmas','https://fc25-club-packs.ea.com/uploads/ud-las-palmas/emblem/ud-las-palmas.png');
INSERT INTO team(TEAM,URL) VALUES ('UD Tenerife','https://fc25-club-packs.ea.com/uploads/ud-tenerife/emblem/ud-tenerife.png');
INSERT INTO team(TEAM,URL) VALUES ('USL Dunkerque','https://fc25-club-packs.ea.com/uploads/usl-dunkerque/emblem/usl-dunkerque.png');
INSERT INTO team(TEAM,URL) VALUES ('UTA Arad','https://fc25-club-packs.ea.com/uploads/uta-arad/emblem/uta-arad.png');
INSERT INTO team(TEAM,URL) VALUES ('Udinese','https://content.sportslogos.net/logos/128/4000/thumbs/3g2fy5sbljbeegc2f8o1qh1nx.gif');
INSERT INTO team(TEAM,URL) VALUES ('Ulsan Hyundai','https://content.sportslogos.net/logos/151/4612/thumbs/i4gf9h0nue7g90b134acbhfph.gif');
INSERT INTO team(TEAM,URL) VALUES ('Uni. Católica','https://content.sportslogos.net/logos/124/6729/thumbs/672994502020.gif');
INSERT INTO team(TEAM,URL) VALUES ('Union Berlin','https://fc25-club-packs.ea.com/uploads/union-berlin/emblem/union-berlin.png');
INSERT INTO team(TEAM,URL) VALUES ('Unirea Slobozia','https://fc25-club-packs.ea.com/uploads/unirea-slobozia/emblem/unirea-slobozia.png');
INSERT INTO team(TEAM,URL) VALUES ('Univ. Craiova','https://content.sportslogos.net/logos/133/4210/thumbs/jgmyko2miv1ge55ufc3880483.gif');
INSERT INTO team(TEAM,URL) VALUES ('Universitario','https://content.sportslogos.net/logos/133/4208/thumbs/nlk6q0mqk36agm6hbhhti39nk.gif');
INSERT INTO team(TEAM,URL) VALUES ('Unión','https://content.sportslogos.net/logos/133/4208/thumbs/nlk6q0mqk36agm6hbhhti39nk.gif');
INSERT INTO team(TEAM,URL) VALUES ('Unión La Calera','https://content.sportslogos.net/logos/133/4210/thumbs/jgmyko2miv1ge55ufc3880483.gif');
INSERT INTO team(TEAM,URL) VALUES ('Unterhaching','https://content.sportslogos.net/logos/124/6729/thumbs/672994502020.gif');
INSERT INTO team(TEAM,URL) VALUES ('Utah Royals FC','https://content.sportslogos.net/logos/133/4185/thumbs/bszwbsbzlcvxq4ac1d66ddv5i.gif');
INSERT INTO team(TEAM,URL) VALUES ('Valencia CF','https://content.sportslogos.net/logos/202/6574/thumbs/657467452018.gif');
INSERT INTO team(TEAM,URL) VALUES ('Vejle Boldklub','https://content.sportslogos.net/logos/130/4161/thumbs/3suj5se5gaqdtqrdrqd2gedaa.gif');
INSERT INTO team(TEAM,URL) VALUES ('Venezia','https://fc25-club-packs.ea.com/uploads/v-ster-s-sk/emblem/v-ster-s-sk.png');
INSERT INTO team(TEAM,URL) VALUES ('VfB Stuttgart','https://fc25-club-packs.ea.com/uploads/vejle-boldklub/emblem/vejle-boldklub.png');
INSERT INTO team(TEAM,URL) VALUES ('VfB Stuttgart II','https://content.sportslogos.net/logos/133/4212/thumbs/n8fxhoc9n13wf9ehchzgdg1j8.gif');
INSERT INTO team(TEAM,URL) VALUES ('VfL Bochum 1848','https://fc25-club-packs.ea.com/uploads/venezia/emblem/venezia.png');
INSERT INTO team(TEAM,URL) VALUES ('VfL Osnabrück','https://content.sportslogos.net/logos/132/4083/thumbs/yermfwxhbbkyumoogv9pvgqkb.gif');
INSERT INTO team(TEAM,URL) VALUES ('VfL Wolfsburg','https://content.sportslogos.net/logos/132/4083/thumbs/yermfwxhbbkyumoogv9pvgqkb.gif');
INSERT INTO team(TEAM,URL) VALUES ('Viborg FF','https://fc25-club-packs.ea.com/uploads/vfl-bochum-1848/emblem/vfl-bochum-1848.png');
INSERT INTO team(TEAM,URL) VALUES ('Viking FK','https://fc25-club-packs.ea.com/uploads/vfl-osnabr-ck/emblem/vfl-osnabr-ck.png');
INSERT INTO team(TEAM,URL) VALUES ('Viktoria Köln','https://content.sportslogos.net/logos/132/4070/thumbs/9iux6r2oynq4dk3dfwm0rj3jy.gif');
INSERT INTO team(TEAM,URL) VALUES ('Viktoria Plzeň','https://content.sportslogos.net/logos/160/4910/thumbs/491011350.gif');
INSERT INTO team(TEAM,URL) VALUES ('Villarreal CF','https://fc25-club-packs.ea.com/uploads/viking-fk/emblem/viking-fk.png');
INSERT INTO team(TEAM,URL) VALUES ('Vitória SC','https://fc25-club-packs.ea.com/uploads/viktoria-k-ln/emblem/viktoria-k-ln.png');
INSERT INTO team(TEAM,URL) VALUES ('Västerås SK','https://en.wikipedia.org/wiki/FC_Viktoria_Plze%C5%88#/media/File:Viktoria_Plzen_logo.svg');
INSERT INTO team(TEAM,URL) VALUES ('Vélez Sarsfield','https://content.sportslogos.net/logos/130/4037/thumbs/h2qdg39za55l1mxhftw5p4i9d.gif');
INSERT INTO team(TEAM,URL) VALUES ('WS Wanderers','https://content.sportslogos.net/logos/179/5346/thumbs/534666770.gif');
INSERT INTO team(TEAM,URL) VALUES ('WSG Tirol','https://content.sportslogos.net/logos/231/6719/thumbs/671961142019.gif');
INSERT INTO team(TEAM,URL) VALUES ('Walsall','https://fc25-club-packs.ea.com/uploads/wsg-tirol/emblem/wsg-tirol.png');
INSERT INTO team(TEAM,URL) VALUES ('Wanderers','https://fc25-club-packs.ea.com/uploads/walsall/emblem/walsall.png');
INSERT INTO team(TEAM,URL) VALUES ('Washington Spirit','https://content.sportslogos.net/logos/231/6719/thumbs/671961142019.gif');
INSERT INTO team(TEAM,URL) VALUES ('Waterford','https://content.sportslogos.net/logos/202/5862/thumbs/586286502013.gif');
INSERT INTO team(TEAM,URL) VALUES ('Watford','https://fc25-club-packs.ea.com/uploads/waterford/emblem/waterford.png');
INSERT INTO team(TEAM,URL) VALUES ('Wehen Wiesbaden','https://fc25-club-packs.ea.com/uploads/watford/emblem/watford.png');
INSERT INTO team(TEAM,URL) VALUES ('Well. Phoenix','https://fc25-club-packs.ea.com/uploads/wehen-wiesbaden/emblem/wehen-wiesbaden.png');
INSERT INTO team(TEAM,URL) VALUES ('West Brom','https://content.sportslogos.net/logos/138/4341/thumbs/wyh6fo6qso4sj1vjbfdw3tehq.gif');
INSERT INTO team(TEAM,URL) VALUES ('West Ham','https://fc25-club-packs.ea.com/uploads/west-brom/emblem/west-brom.png');
INSERT INTO team(TEAM,URL) VALUES ('Western United','https://content.sportslogos.net/logos/203/5879/thumbs/587991692015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Whitecaps FC','https://content.sportslogos.net/logos/142/4440/thumbs/07vftmh4wbbc55x585wpvhl6f.gif');
INSERT INTO team(TEAM,URL) VALUES ('Widzew Łódź','https://content.sportslogos.net/logos/124/5489/thumbs/548936102015.gif');
INSERT INTO team(TEAM,URL) VALUES ('Wigan Athletic','https://fc25-club-packs.ea.com/uploads/widzew-d/emblem/widzew-d.png');
INSERT INTO team(TEAM,URL) VALUES ('Willem II','https://content.sportslogos.net/logos/141/5886/thumbs/588651502017.gif');
INSERT INTO team(TEAM,URL) VALUES ('Wilstermann','https://content.sportslogos.net/logos/180/5367/thumbs/536745170.gif');
INSERT INTO team(TEAM,URL) VALUES ('Wolfsberger AC','https://fc25-club-packs.ea.com/uploads/wilstermann/emblem/wilstermann.png');
INSERT INTO team(TEAM,URL) VALUES ('Wolves','https://fc25-club-packs.ea.com/uploads/wolfsberger-ac/emblem/wolfsberger-ac.png');
INSERT INTO team(TEAM,URL) VALUES ('Wrexham','https://fc25-club-packs.ea.com/uploads/wolves/emblem/wolves.png');
INSERT INTO team(TEAM,URL) VALUES ('Wuhan Three Towns','https://fc25-club-packs.ea.com/uploads/wrexham/emblem/wrexham.png');
INSERT INTO team(TEAM,URL) VALUES ('Wycombe','https://fc25-club-packs.ea.com/uploads/wuhan-three-towns/emblem/wuhan-three-towns.png');
INSERT INTO team(TEAM,URL) VALUES ('Yverdon Sport FC','https://fc25-club-packs.ea.com/uploads/wycombe/emblem/wycombe.png');
INSERT INTO team(TEAM,URL) VALUES ('Zagłębie Lubin','https://fc25-club-packs.ea.com/uploads/yverdon-sport-fc/emblem/yverdon-sport-fc.png');
INSERT INTO team(TEAM,URL) VALUES ('Zhejiang Pro','https://fc25-club-packs.ea.com/uploads/zag-bie-lubin/emblem/zag-bie-lubin.png');
INSERT INTO team(TEAM,URL) VALUES ('sc Heerenveen','https://content.sportslogos.net/logos/152/4648/thumbs/uwl4gf7tc44wfzbuuhtoutfj5.gif');
INSERT INTO team(TEAM,URL) VALUES ('Çaykur Rizespor','https://content.sportslogos.net/logos/180/5363/thumbs/536329830.gif');
INSERT INTO team(TEAM,URL) VALUES ('Śląsk Wrocław','https://fc25-club-packs.ea.com/uploads/l-sk-wroc-aw/emblem/l-sk-wroc-aw.png');

-- leauge
INSERT INTO league(name,url) VALUES ('1A Pro League','https://upload.wikimedia.org/wikipedia/commons/d/db/Pro_League_logo2020.jpg');
INSERT INTO league(name,url) VALUES ('3. Liga','https://upload.wikimedia.org/wikipedia/en/b/bc/3._Liga_logo_%282019%29.svg');
INSERT INTO league(name,url) VALUES ('3F Superliga','https://upload.wikimedia.org/wikipedia/commons/6/68/3F_Superliga_Logo_2024.png');
INSERT INTO league(name,url) VALUES ('A-League','https://upload.wikimedia.org/wikipedia/en/9/98/Isuzu_UTE_A-League_Men.svg');
INSERT INTO league(name,url) VALUES ('Allsvenskan','https://upload.wikimedia.org/wikipedia/en/4/4a/Allsvenskan_logo.svg');
INSERT INTO league(name,url) VALUES ('Arkema PL','https://upload.wikimedia.org/wikipedia/en/7/74/Premi%C3%A8re_Ligue.png');
INSERT INTO league(name,url) VALUES ('Barclays WSL','https://upload.wikimedia.org/wikipedia/en/4/4f/FA_Women%27s_Super_League.png');
INSERT INTO league(name,url) VALUES ('Bundesliga','https://upload.wikimedia.org/wikipedia/en/d/df/Bundesliga_logo_%282017%29.svg');
INSERT INTO league(name,url) VALUES ('Bundesliga 2','https://upload.wikimedia.org/wikipedia/en/7/7b/2._Bundesliga_logo.svg');
INSERT INTO league(name,url) VALUES ('CSL','https://upload.wikimedia.org/wikipedia/en/8/8e/Chinese_Super_League.svg');
INSERT INTO league(name,url) VALUES ('CSSL','https://i.namu.wiki/i/nWjdzHOlCU-vRVRjc9ZOpzycRAcx…k1zYqMHmrNLwY6kv8NEo2etFnV_HKWMhzd2UOywrussHg.svg');
INSERT INTO league(name,url) VALUES ('Calcio A Femminile','https://upload.wikimedia.org/wikipedia/it/7/7f/FIGC_Serie_A_femminile_%282020%29.svg');
INSERT INTO league(name,url) VALUES ('Ceska Liga Zen','');
INSERT INTO league(name,url) VALUES ('Chance liga','');
INSERT INTO league(name,url) VALUES ('EFL Championship','https://upload.wikimedia.org/wikipedia/en/0/0f/EFL_Championship_Logo.svg');
INSERT INTO league(name,url) VALUES ('EFL League One','https://upload.wikimedia.org/wikipedia/en/5/53/EFL_League_One_Logo.svg');
INSERT INTO league(name,url) VALUES ('EFL League Two','https://upload.wikimedia.org/wikipedia/en/9/93/EFL_League_Two_Logo.svg');
INSERT INTO league(name,url) VALUES ('Eliteserien','https://upload.wikimedia.org/wikipedia/commons/8/81/Eliteserien_logo.jpg');
INSERT INTO league(name,url) VALUES ('Eredivisie','https://upload.wikimedia.org/wikipedia/commons/0/0f/Eredivisie_nieuw_logo_2017-.svg');
INSERT INTO league(name,url) VALUES ('Finnliiga','https://upload.wikimedia.org/wikipedia/en/4/46/Veikkausliiga_logo_2025.png');
INSERT INTO league(name,url) VALUES ('GPFBL','https://en.wikipedia.org/wiki/Frauen-Bundesliga#/media/File:Frauen-Bundesliga_logo_(2019).svg');
INSERT INTO league(name,url) VALUES ('Hellas Liga','https://upload.wikimedia.org/wikipedia/en/5/54/Super_League_Greece_logo.svg');
INSERT INTO league(name,url) VALUES ('ISL','https://upload.wikimedia.org/wikipedia/en/b/b0/Indian_Super_League_logo.svg');
INSERT INTO league(name,url) VALUES ('K League 1','https://upload.wikimedia.org/wikipedia/ko/c/ca/K%EB%A6%AC%EA%B7%B81_%EB%A1%9C%EA%B3%A0.png');
INSERT INTO league(name,url) VALUES ('LALIGA EA SPORTS','https://upload.wikimedia.org/wikipedia/commons/5/54/LaLiga_EA_Sports_2023_Vertical_Logo.svg');
INSERT INTO league(name,url) VALUES ('LALIGA HYPERMOTION','');
INSERT INTO league(name,url) VALUES ('Libertadores','https://upload.wikimedia.org/wikipedia/en/a/a1/Copa_Libertadores_logo.svg');
INSERT INTO league(name,url) VALUES ('Liga Azerbaijan','https://upload.wikimedia.org/wikipedia/en/c/c5/Azerbaijan_Premier_League_logo.png');
INSERT INTO league(name,url) VALUES ('Liga Colombia','https://upload.wikimedia.org/wikipedia/commons/e/e0/BetPlay-Dimayor_logo.svg');
INSERT INTO league(name,url) VALUES ('Liga Cyprus','');
INSERT INTO league(name,url) VALUES ('Liga F','https://upload.wikimedia.org/wikipedia/en/b/b3/Ligafwomen.svg');
INSERT INTO league(name,url) VALUES ('Liga Hrvatska','https://upload.wikimedia.org/wikipedia/hr/2/29/Hrvatska_nogometna_liga_2022.png');
INSERT INTO league(name,url) VALUES ('Liga Portugal','https://upload.wikimedia.org/wikipedia/commons/5/55/Primeira_Liga_204_Logo.png');
INSERT INTO league(name,url) VALUES ('Liga Portugal Feminino','https://upload.wikimedia.org/wikipedia/commons/6/6a/Liga_BPI_logo.png');
INSERT INTO league(name,url) VALUES ('Ligue 1 McDonald''s','https://upload.wikimedia.org/wikipedia/fr/7/7b/Logo_Ligue_1_McDonald%27s_2024.svg');
INSERT INTO league(name,url) VALUES ('Ligue 2 BKT','https://upload.wikimedia.org/wikipedia/commons/b/b4/Ligue_2_2024_Logo.png');
INSERT INTO league(name,url) VALUES ('MLS','https://upload.wikimedia.org/wikipedia/commons/7/76/MLS_crest_logo_RGB_gradient.svg');
INSERT INTO league(name,url) VALUES ('Magyar Liga','https://upload.wikimedia.org/wikipedia/commons/9/96/OTP_Bank_Liga_logo.png');
INSERT INTO league(name,url) VALUES ('NWSL','');
INSERT INTO league(name,url) VALUES ('Nederland Vrouwen Liga','https://upload.wikimedia.org/wikipedia/en/0/0e/Vrouwen_Eredivisie_logo.jpg');
INSERT INTO league(name,url) VALUES ('O. Bundesliga','https://upload.wikimedia.org/wikipedia/en/2/29/Admiral_Bundesliga.svg');
INSERT INTO league(name,url) VALUES ('PKO BP Ekstraklasa','');
INSERT INTO league(name,url) VALUES ('Premier League','https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg');
INSERT INTO league(name,url) VALUES ('Primera Divisio','https://upload.wikimedia.org/wikipedia/commons/1/16/Multisegur_league_badge.png');
INSERT INTO league(name,url) VALUES ('ROSHN Saudi League','https://upload.wikimedia.org/wikipedia/en/7/75/Roshn_Saudi_League_Logo.svg');
INSERT INTO league(name,url) VALUES ('SSE Airtricity PD','https://upload.wikimedia.org/wikipedia/commons/f/f7/League_Of_Ireland_Logo_2023.webp');
INSERT INTO league(name,url) VALUES ('SUPERLIGA','https://upload.wikimedia.org/wikipedia/commons/6/68/3F_Superliga_Logo_2024.png');
INSERT INTO league(name,url) VALUES ('Schweizer Damen Liga','https://www.awsl.ch/Portaldata/27/Resources/bilder/frauenfussball/awsl/logo/AWSL_Logo.png');
INSERT INTO league(name,url) VALUES ('Scottish Prem','https://spfl.co.uk/cms-content/images/shares/spons…spfl-stats-centre-logo-reversed-home-page_480.png');
INSERT INTO league(name,url) VALUES ('Scottish Women''s League','https://upload.wikimedia.org/wikipedia/commons/c/cc/SWPL_Logo_Brandmarque_Colour.png');
INSERT INTO league(name,url) VALUES ('Serie A Enilive','https://upload.wikimedia.org/wikipedia/en/a/ab/Serie_A_ENILIVE_logo.svg');
INSERT INTO league(name,url) VALUES ('Serie BKT','https://upload.wikimedia.org/wikipedia/en/9/90/Serie_BKT_logo.svg');
INSERT INTO league(name,url) VALUES ('Sudamericana','https://upload.wikimedia.org/wikipedia/en/c/c2/CONMEBOL_Sudamericana_logo_%282017%29.svg');
INSERT INTO league(name,url) VALUES ('Sverige Liga','https://upload.wikimedia.org/wikipedia/en/4/4a/Allsvenskan_logo.svg');
INSERT INTO league(name,url) VALUES ('Trendyol Super Lig','https://upload.wikimedia.org/wikipedia/commons/8/86/Trendyol_super_lig_logo.svg');
INSERT INTO league(name,url) VALUES ('Ukrayina Liha','https://upload.wikimedia.org/wikipedia/commons/e/e9/%D0%9E%D1%84%D1%96%D1%86%D1%96%D0%B9%D0%BD%D0%B0_%D0%B5%D0%BC%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0_%D0%9F%D1%80%D0%B5%D0%BC%27%D1%94%D1%80-%D0%9B%D1%96%D0%B3%D0%B8.png');
INSERT INTO league(name,url) VALUES ('United Emirates League','https://upload.wikimedia.org/wikipedia/en/0/07/UAE_Pro_League_logo.svg');